import type { WorkspaceNotification } from './types'
import { isoDaysAgo, withPreviewModeSearchParam } from './utils'

export function getPreviewNotifications(clientId: string | null = null): WorkspaceNotification[] {
    const notifications: WorkspaceNotification[] = [
        {
            id: 'preview-notif-1',
            kind: 'task.updated',
            title: 'Task assigned to you',
            body: 'You have been assigned to "Review Q3 performance report"',
            actor: { id: 'preview-user-1', name: 'Alex Morgan' },
            resource: { type: 'task', id: 'preview-task-1' },
            recipients: { roles: ['team'], clientId: 'preview-tech-corp', clientIds: ['preview-tech-corp'] },
            navigationUrl: '/dashboard/tasks?taskId=preview-task-1',
            createdAt: isoDaysAgo(0),
            updatedAt: isoDaysAgo(0),
            read: false,
            acknowledged: false,
        },
        {
            id: 'preview-notif-2',
            kind: 'collaboration.mention',
            title: 'You were mentioned',
            body: 'Priya Patel mentioned you in "Product Launch Marketing"',
            actor: { id: 'preview-user-2', name: 'Priya Patel' },
            resource: { type: 'collaboration', id: 'preview-message-1' },
            recipients: { roles: ['team'], clientId: 'preview-startupxyz', clientIds: ['preview-startupxyz'] },
            navigationUrl: '/dashboard/collaboration?projectId=preview-project-2',
            createdAt: isoDaysAgo(1),
            updatedAt: isoDaysAgo(1),
            read: false,
            acknowledged: false,
        },
        {
            id: 'preview-notif-3',
            kind: 'proposal.deck.ready',
            title: 'Proposal deck ready',
            body: 'Your presentation for Tech Corp is ready to download',
            actor: { id: null, name: 'System' },
            resource: { type: 'proposal', id: 'preview-proposal-1' },
            recipients: { roles: ['team'], clientId: 'preview-tech-corp', clientIds: ['preview-tech-corp'] },
            navigationUrl: withPreviewModeSearchParam('/dashboard/proposals/preview-proposal-1/deck'),
            createdAt: isoDaysAgo(2),
            updatedAt: isoDaysAgo(2),
            read: true,
            acknowledged: false,
        },
        {
            id: 'preview-notif-4',
            kind: 'task.mention',
            title: 'Mentioned in a task comment',
            body: 'Jordan Lee asked for revised KPI targets on the growth sprint task.',
            actor: { id: 'preview-user-3', name: 'Jordan Lee' },
            resource: { type: 'task', id: 'preview-task-2' },
            recipients: { roles: ['team'], clientId: 'preview-tech-corp', clientIds: ['preview-tech-corp'] },
            navigationUrl: '/dashboard/tasks?taskId=preview-task-2',
            createdAt: isoDaysAgo(3),
            updatedAt: isoDaysAgo(3),
            read: false,
            acknowledged: false,
        },
        {
            id: 'preview-notif-5',
            kind: 'project.created',
            title: 'New project created',
            body: 'Social Media Management project has been set up for Tech Corp',
            actor: { id: 'preview-user-1', name: 'Alex Morgan' },
            resource: { type: 'project', id: 'preview-project-4' },
            recipients: { roles: ['team'], clientId: 'preview-tech-corp', clientIds: ['preview-tech-corp'] },
            navigationUrl: '/dashboard/projects?projectId=preview-project-4',
            createdAt: isoDaysAgo(5),
            updatedAt: isoDaysAgo(5),
            read: true,
            acknowledged: true,
        },
        {
            id: 'preview-notif-6',
            kind: 'task.comment',
            title: 'New task comment',
            body: 'Mia Thompson left feedback on the paid social motion cutdowns task.',
            actor: { id: 'preview-user-7', name: 'Mia Thompson' },
            resource: { type: 'task', id: 'preview-task-7' },
            recipients: { roles: ['team'], clientId: 'preview-tech-corp', clientIds: ['preview-tech-corp'] },
            navigationUrl: '/dashboard/tasks?taskId=preview-task-7',
            createdAt: isoDaysAgo(0),
            updatedAt: isoDaysAgo(0),
            read: false,
            acknowledged: false,
        },
        {
            id: 'preview-notif-7',
            kind: 'collaboration.message',
            title: 'New client channel update',
            body: 'Taylor Kim posted a holiday revenue recap in the Retail Store channel.',
            actor: { id: 'preview-user-5', name: 'Taylor Kim' },
            resource: { type: 'collaboration', id: 'preview-collab-client-3' },
            recipients: { roles: ['team'], clientId: 'preview-retail-store', clientIds: ['preview-retail-store'] },
            navigationUrl: '/dashboard/collaboration?clientId=preview-retail-store',
            createdAt: isoDaysAgo(1),
            updatedAt: isoDaysAgo(1),
            read: true,
            acknowledged: false,
        },
        {
            id: 'preview-notif-8',
            kind: 'task.created',
            title: 'Task added to launch project',
            body: 'A new launch QA task was created for StartupXYZ.',
            actor: { id: 'preview-user-3', name: 'Priya Patel' },
            resource: { type: 'task', id: 'preview-task-5' },
            recipients: { roles: ['team'], clientId: 'preview-startupxyz', clientIds: ['preview-startupxyz'] },
            navigationUrl: '/dashboard/tasks?taskId=preview-task-5',
            createdAt: isoDaysAgo(2),
            updatedAt: isoDaysAgo(2),
            read: false,
            acknowledged: false,
        },
        {
            id: 'preview-notif-9',
            kind: 'proposal.deck.ready',
            title: 'Launch deck regenerated',
            body: 'StartupXYZ presentation deck has been regenerated with updated launch messaging.',
            actor: { id: null, name: 'System' },
            resource: { type: 'proposal', id: 'preview-proposal-2' },
            recipients: { roles: ['team'], clientId: 'preview-startupxyz', clientIds: ['preview-startupxyz'] },
            navigationUrl: withPreviewModeSearchParam('/dashboard/proposals/preview-proposal-2/deck'),
            createdAt: isoDaysAgo(3),
            updatedAt: isoDaysAgo(3),
            read: true,
            acknowledged: false,
        },
        {
            id: 'preview-notif-10',
            kind: 'collaboration.mention',
            title: 'Mentioned in team ops',
            body: 'Casey Rivera mentioned you in the morning ops thread about client approvals.',
            actor: { id: 'preview-user-6', name: 'Casey Rivera' },
            resource: { type: 'collaboration', id: 'preview-collab-team-1' },
            recipients: { roles: ['team'] },
            navigationUrl: '/dashboard/collaboration?channel=team',
            createdAt: isoDaysAgo(4),
            updatedAt: isoDaysAgo(4),
            read: false,
            acknowledged: false,
        },
    ]

    if (!clientId) {
        return notifications
    }

    return notifications.filter((notification) => {
        const recipientIds = [
            notification.recipients.clientId ?? null,
            ...(notification.recipients.clientIds ?? []),
        ].filter((value): value is string => typeof value === 'string' && value.length > 0)

        return recipientIds.length === 0 || recipientIds.includes(clientId)
    })
}
