/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as activity from "../activity.js";
import type * as adSyncWorker from "../adSyncWorker.js";
import type * as adSyncWorkerActions from "../adSyncWorkerActions.js";
import type * as adminFeatures from "../adminFeatures.js";
import type * as adminFeaturesAi from "../adminFeaturesAi.js";
import type * as adminInvitations from "../adminInvitations.js";
import type * as adminMigrations from "../adminMigrations.js";
import type * as adminNotifications from "../adminNotifications.js";
import type * as adminUsage from "../adminUsage.js";
import type * as adminUserPage from "../adminUserPage.js";
import type * as adminUsers from "../adminUsers.js";
import type * as adsAdMetrics from "../adsAdMetrics.js";
import type * as adsAdSets from "../adsAdSets.js";
import type * as adsAudiences from "../adsAudiences.js";
import type * as adsAudiencesMeta from "../adsAudiencesMeta.js";
import type * as adsCampaignGroups from "../adsCampaignGroups.js";
import type * as adsCampaignInsights from "../adsCampaignInsights.js";
import type * as adsCampaigns from "../adsCampaigns.js";
import type * as adsCreatives from "../adsCreatives.js";
import type * as adsIntegrations from "../adsIntegrations.js";
import type * as adsMetaCampaigns from "../adsMetaCampaigns.js";
import type * as adsMetaEvents from "../adsMetaEvents.js";
import type * as adsMetaTools from "../adsMetaTools.js";
import type * as adsMetrics from "../adsMetrics.js";
import type * as adsTargeting from "../adsTargeting.js";
import type * as agent from "../agent.js";
import type * as agentActions from "../agentActions.js";
import type * as agentAttachments from "../agentAttachments.js";
import type * as agentConversations from "../agentConversations.js";
import type * as agentMessages from "../agentMessages.js";
import type * as alertRules from "../alertRules.js";
import type * as analyticsInsights from "../analyticsInsights.js";
import type * as analyticsIntegrations from "../analyticsIntegrations.js";
import type * as apiIdempotency from "../apiIdempotency.js";
import type * as appProxy from "../appProxy.js";
import type * as artifactArchiveBackfills from "../artifactArchiveBackfills.js";
import type * as auditLogs from "../auditLogs.js";
import type * as auth from "../auth.js";
import type * as authActions from "../authActions.js";
import type * as clientAdminTeamSync from "../clientAdminTeamSync.js";
import type * as clients from "../clients.js";
import type * as collaborationChannelAvatars from "../collaborationChannelAvatars.js";
import type * as collaborationChannels from "../collaborationChannels.js";
import type * as collaborationMessages from "../collaborationMessages.js";
import type * as collaborationTyping from "../collaborationTyping.js";
import type * as conversationRouting from "../conversationRouting.js";
import type * as creativesCopy from "../creativesCopy.js";
import type * as crons from "../crons.js";
import type * as customFormulas from "../customFormulas.js";
import type * as debug from "../debug.js";
import type * as deepseekRateLimit from "../deepseekRateLimit.js";
import type * as directMessages from "../directMessages.js";
import type * as domains_collaboration_collaborationChannelAvatars from "../domains/collaboration/collaborationChannelAvatars.js";
import type * as domains_collaboration_collaborationChannels from "../domains/collaboration/collaborationChannels.js";
import type * as domains_collaboration_collaborationMessages_listing from "../domains/collaboration/collaborationMessages/listing.js";
import type * as domains_collaboration_collaborationMessages_messageMutations from "../domains/collaboration/collaborationMessages/messageMutations.js";
import type * as domains_collaboration_collaborationMessages_readTracking from "../domains/collaboration/collaborationMessages/readTracking.js";
import type * as domains_collaboration_collaborationMessages_shared from "../domains/collaboration/collaborationMessages/shared.js";
import type * as domains_collaboration_collaborationMessages_syncAndPins from "../domains/collaboration/collaborationMessages/syncAndPins.js";
import type * as domains_collaboration_collaborationTyping from "../domains/collaboration/collaborationTyping.js";
import type * as domains_collaboration_conversationRouting from "../domains/collaboration/conversationRouting.js";
import type * as domains_collaboration_directMessages_conversations from "../domains/collaboration/directMessages/conversations.js";
import type * as domains_collaboration_directMessages_messages from "../domains/collaboration/directMessages/messages.js";
import type * as domains_collaboration_directMessages_pollsAndReactions from "../domains/collaboration/directMessages/pollsAndReactions.js";
import type * as domains_collaboration_directMessages_shared from "../domains/collaboration/directMessages/shared.js";
import type * as domains_collaboration_inboxItems from "../domains/collaboration/inboxItems.js";
import type * as domains_collaboration_messageAnalytics from "../domains/collaboration/messageAnalytics.js";
import type * as domains_marketing_adSyncWorker from "../domains/marketing/adSyncWorker.js";
import type * as domains_marketing_adSyncWorkerActions from "../domains/marketing/adSyncWorkerActions.js";
import type * as domains_marketing_adsAdMetrics from "../domains/marketing/adsAdMetrics.js";
import type * as domains_marketing_adsAdSets from "../domains/marketing/adsAdSets.js";
import type * as domains_marketing_adsAudiences from "../domains/marketing/adsAudiences.js";
import type * as domains_marketing_adsAudiencesMeta from "../domains/marketing/adsAudiencesMeta.js";
import type * as domains_marketing_adsCampaignGroups from "../domains/marketing/adsCampaignGroups.js";
import type * as domains_marketing_adsCampaignInsights from "../domains/marketing/adsCampaignInsights.js";
import type * as domains_marketing_adsCampaigns from "../domains/marketing/adsCampaigns.js";
import type * as domains_marketing_adsCreatives from "../domains/marketing/adsCreatives.js";
import type * as domains_marketing_adsCreativesActions_createCreative from "../domains/marketing/adsCreativesActions/createCreative.js";
import type * as domains_marketing_adsCreativesActions_listCreatives from "../domains/marketing/adsCreativesActions/listCreatives.js";
import type * as domains_marketing_adsCreativesActions_listMetaPageActors from "../domains/marketing/adsCreativesActions/listMetaPageActors.js";
import type * as domains_marketing_adsCreativesActions_shared from "../domains/marketing/adsCreativesActions/shared.js";
import type * as domains_marketing_adsCreativesActions_updateCreative from "../domains/marketing/adsCreativesActions/updateCreative.js";
import type * as domains_marketing_adsCreativesActions_updateCreativeStatus from "../domains/marketing/adsCreativesActions/updateCreativeStatus.js";
import type * as domains_marketing_adsCreativesActions_uploadMedia from "../domains/marketing/adsCreativesActions/uploadMedia.js";
import type * as domains_marketing_adsIntegrations_accountInit from "../domains/marketing/adsIntegrations/accountInit.js";
import type * as domains_marketing_adsIntegrations_credentialsStatus from "../domains/marketing/adsIntegrations/credentialsStatus.js";
import type * as domains_marketing_adsIntegrations_discovery from "../domains/marketing/adsIntegrations/discovery.js";
import type * as domains_marketing_adsIntegrations_metricsDeletion from "../domains/marketing/adsIntegrations/metricsDeletion.js";
import type * as domains_marketing_adsIntegrations_queries from "../domains/marketing/adsIntegrations/queries.js";
import type * as domains_marketing_adsIntegrations_settings from "../domains/marketing/adsIntegrations/settings.js";
import type * as domains_marketing_adsIntegrations_shared from "../domains/marketing/adsIntegrations/shared.js";
import type * as domains_marketing_adsIntegrations_syncJobs from "../domains/marketing/adsIntegrations/syncJobs.js";
import type * as domains_marketing_adsMetaCampaigns from "../domains/marketing/adsMetaCampaigns.js";
import type * as domains_marketing_adsMetaEvents from "../domains/marketing/adsMetaEvents.js";
import type * as domains_marketing_adsMetaTools from "../domains/marketing/adsMetaTools.js";
import type * as domains_marketing_adsMetrics from "../domains/marketing/adsMetrics.js";
import type * as domains_marketing_adsTargeting from "../domains/marketing/adsTargeting.js";
import type * as domains_marketing_analyticsInsights from "../domains/marketing/analyticsInsights.js";
import type * as domains_marketing_analyticsIntegrations_accountInit from "../domains/marketing/analyticsIntegrations/accountInit.js";
import type * as domains_marketing_analyticsIntegrations_discovery from "../domains/marketing/analyticsIntegrations/discovery.js";
import type * as domains_marketing_analyticsIntegrations_metrics from "../domains/marketing/analyticsIntegrations/metrics.js";
import type * as domains_marketing_analyticsIntegrations_queries from "../domains/marketing/analyticsIntegrations/queries.js";
import type * as domains_marketing_analyticsIntegrations_settings from "../domains/marketing/analyticsIntegrations/settings.js";
import type * as domains_marketing_analyticsIntegrations_shared from "../domains/marketing/analyticsIntegrations/shared.js";
import type * as domains_marketing_creativesCopy from "../domains/marketing/creativesCopy.js";
import type * as domains_marketing_customFormulas from "../domains/marketing/customFormulas.js";
import type * as domains_marketing_metaWebhookEvents from "../domains/marketing/metaWebhookEvents.js";
import type * as domains_marketing_socialIntegrations_discovery from "../domains/marketing/socialIntegrations/discovery.js";
import type * as domains_marketing_socialIntegrations_metricsUpsert from "../domains/marketing/socialIntegrations/metricsUpsert.js";
import type * as domains_marketing_socialIntegrations_queries from "../domains/marketing/socialIntegrations/queries.js";
import type * as domains_marketing_socialIntegrations_settings from "../domains/marketing/socialIntegrations/settings.js";
import type * as domains_marketing_socialIntegrations_syncJobs from "../domains/marketing/socialIntegrations/syncJobs.js";
import type * as domains_marketing_socialMetrics from "../domains/marketing/socialMetrics.js";
import type * as domains_marketing_socialSyncWorkerActions from "../domains/marketing/socialSyncWorkerActions.js";
import type * as domains_ops_alertRules from "../domains/ops/alertRules.js";
import type * as domains_ops_gamma from "../domains/ops/gamma.js";
import type * as domains_ops_meetingArchiveActions from "../domains/ops/meetingArchiveActions.js";
import type * as domains_ops_meetingArchives from "../domains/ops/meetingArchives.js";
import type * as domains_ops_meetingIntegrations from "../domains/ops/meetingIntegrations.js";
import type * as domains_ops_meetings from "../domains/ops/meetings.js";
import type * as domains_ops_notificationTargeting from "../domains/ops/notificationTargeting.js";
import type * as domains_ops_notifications from "../domains/ops/notifications.js";
import type * as domains_ops_presentationDeck from "../domains/ops/presentationDeck.js";
import type * as domains_ops_proposalAnalytics from "../domains/ops/proposalAnalytics.js";
import type * as domains_ops_proposalArchiveActions from "../domains/ops/proposalArchiveActions.js";
import type * as domains_ops_proposalArchives from "../domains/ops/proposalArchives.js";
import type * as domains_ops_proposalGeneration from "../domains/ops/proposalGeneration.js";
import type * as domains_ops_proposalVersions from "../domains/ops/proposalVersions.js";
import type * as domains_ops_proposals from "../domains/ops/proposals.js";
import type * as domains_ops_schedulerAlertPreferences from "../domains/ops/schedulerAlertPreferences.js";
import type * as domains_platform_adminFeatures from "../domains/platform/adminFeatures.js";
import type * as domains_platform_adminFeaturesAi from "../domains/platform/adminFeaturesAi.js";
import type * as domains_platform_adminInvitations from "../domains/platform/adminInvitations.js";
import type * as domains_platform_adminMigrations from "../domains/platform/adminMigrations.js";
import type * as domains_platform_adminNotifications from "../domains/platform/adminNotifications.js";
import type * as domains_platform_adminUsage from "../domains/platform/adminUsage.js";
import type * as domains_platform_adminUserPage from "../domains/platform/adminUserPage.js";
import type * as domains_platform_adminUsers from "../domains/platform/adminUsers.js";
import type * as domains_platform_agent from "../domains/platform/agent.js";
import type * as domains_platform_agentActions from "../domains/platform/agentActions.js";
import type * as domains_platform_agentActions_helpers from "../domains/platform/agentActions/helpers.js";
import type * as domains_platform_agentActions_helpers_confirmation from "../domains/platform/agentActions/helpers/confirmation.js";
import type * as domains_platform_agentActions_helpers_context from "../domains/platform/agentActions/helpers/context.js";
import type * as domains_platform_agentActions_helpers_dates from "../domains/platform/agentActions/helpers/dates.js";
import type * as domains_platform_agentActions_helpers_formatting from "../domains/platform/agentActions/helpers/formatting.js";
import type * as domains_platform_agentActions_helpers_intents from "../domains/platform/agentActions/helpers/intents.js";
import type * as domains_platform_agentActions_helpers_intents_execute from "../domains/platform/agentActions/helpers/intents/execute.js";
import type * as domains_platform_agentActions_helpers_intents_index from "../domains/platform/agentActions/helpers/intents/index.js";
import type * as domains_platform_agentActions_helpers_intents_navigation from "../domains/platform/agentActions/helpers/intents/navigation.js";
import type * as domains_platform_agentActions_helpers_intents_parsing from "../domains/platform/agentActions/helpers/intents/parsing.js";
import type * as domains_platform_agentActions_helpers_proposalConversation from "../domains/platform/agentActions/helpers/proposalConversation.js";
import type * as domains_platform_agentActions_helpers_proposals from "../domains/platform/agentActions/helpers/proposals.js";
import type * as domains_platform_agentActions_helpers_values from "../domains/platform/agentActions/helpers/values.js";
import type * as domains_platform_agentActions_operations from "../domains/platform/agentActions/operations.js";
import type * as domains_platform_agentActions_operations_ads from "../domains/platform/agentActions/operations/ads.js";
import type * as domains_platform_agentActions_operations_ads_index from "../domains/platform/agentActions/operations/ads/index.js";
import type * as domains_platform_agentActions_operations_ads_reports from "../domains/platform/agentActions/operations/ads/reports.js";
import type * as domains_platform_agentActions_operations_analyticsSummary from "../domains/platform/agentActions/operations/analyticsSummary.js";
import type * as domains_platform_agentActions_operations_clients from "../domains/platform/agentActions/operations/clients.js";
import type * as domains_platform_agentActions_operations_clients_index from "../domains/platform/agentActions/operations/clients/index.js";
import type * as domains_platform_agentActions_operations_meetings_index from "../domains/platform/agentActions/operations/meetings/index.js";
import type * as domains_platform_agentActions_operations_messaging from "../domains/platform/agentActions/operations/messaging.js";
import type * as domains_platform_agentActions_operations_messaging_index from "../domains/platform/agentActions/operations/messaging/index.js";
import type * as domains_platform_agentActions_operations_notifications_index from "../domains/platform/agentActions/operations/notifications/index.js";
import type * as domains_platform_agentActions_operations_projects from "../domains/platform/agentActions/operations/projects.js";
import type * as domains_platform_agentActions_operations_projects_index from "../domains/platform/agentActions/operations/projects/index.js";
import type * as domains_platform_agentActions_operations_proposals from "../domains/platform/agentActions/operations/proposals.js";
import type * as domains_platform_agentActions_operations_proposals_index from "../domains/platform/agentActions/operations/proposals/index.js";
import type * as domains_platform_agentActions_operations_reports from "../domains/platform/agentActions/operations/reports.js";
import type * as domains_platform_agentActions_operations_shared from "../domains/platform/agentActions/operations/shared.js";
import type * as domains_platform_agentActions_operations_socials_index from "../domains/platform/agentActions/operations/socials/index.js";
import type * as domains_platform_agentActions_operations_socials_socialSummary from "../domains/platform/agentActions/operations/socials/socialSummary.js";
import type * as domains_platform_agentActions_operations_spreadsheet_builders from "../domains/platform/agentActions/operations/spreadsheet/builders.js";
import type * as domains_platform_agentActions_operations_spreadsheet_export from "../domains/platform/agentActions/operations/spreadsheet/export.js";
import type * as domains_platform_agentActions_operations_taskSummary from "../domains/platform/agentActions/operations/taskSummary.js";
import type * as domains_platform_agentActions_operations_tasks from "../domains/platform/agentActions/operations/tasks.js";
import type * as domains_platform_agentActions_operations_tasks_index from "../domains/platform/agentActions/operations/tasks/index.js";
import type * as domains_platform_agentActions_prompting from "../domains/platform/agentActions/prompting.js";
import type * as domains_platform_agentActions_runExecuteTurn from "../domains/platform/agentActions/runExecuteTurn.js";
import type * as domains_platform_agentActions_types from "../domains/platform/agentActions/types.js";
import type * as domains_platform_agentAttachments from "../domains/platform/agentAttachments.js";
import type * as domains_platform_agentConversations from "../domains/platform/agentConversations.js";
import type * as domains_platform_agentMessages from "../domains/platform/agentMessages.js";
import type * as domains_platform_apiIdempotency from "../domains/platform/apiIdempotency.js";
import type * as domains_platform_appProxy from "../domains/platform/appProxy.js";
import type * as domains_platform_artifactArchiveBackfills from "../domains/platform/artifactArchiveBackfills.js";
import type * as domains_platform_auditLogs from "../domains/platform/auditLogs.js";
import type * as domains_platform_auth from "../domains/platform/auth.js";
import type * as domains_platform_authActions from "../domains/platform/authActions.js";
import type * as domains_platform_clientAdminTeamSync from "../domains/platform/clientAdminTeamSync.js";
import type * as domains_platform_debug from "../domains/platform/debug.js";
import type * as domains_platform_deepseekRateLimit from "../domains/platform/deepseekRateLimit.js";
import type * as domains_platform_health from "../domains/platform/health.js";
import type * as domains_platform_httpActions from "../domains/platform/httpActions.js";
import type * as domains_platform_migrations_adMetricsCurrency from "../domains/platform/migrations/adMetricsCurrency.js";
import type * as domains_platform_migrations_adminDiagnostics from "../domains/platform/migrations/adminDiagnostics.js";
import type * as domains_platform_migrations_clientAdminTeam from "../domains/platform/migrations/clientAdminTeam.js";
import type * as domains_platform_migrations_taskAssigneePools from "../domains/platform/migrations/taskAssigneePools.js";
import type * as domains_platform_onboardingStates from "../domains/platform/onboardingStates.js";
import type * as domains_platform_privacyMasks from "../domains/platform/privacyMasks.js";
import type * as domains_platform_problemReports from "../domains/platform/problemReports.js";
import type * as domains_platform_rateLimit from "../domains/platform/rateLimit.js";
import type * as domains_platform_rateLimitApi from "../domains/platform/rateLimitApi.js";
import type * as domains_platform_schedulerEvents from "../domains/platform/schedulerEvents.js";
import type * as domains_platform_serverCache from "../domains/platform/serverCache.js";
import type * as domains_platform_settings from "../domains/platform/settings.js";
import type * as domains_platform_users from "../domains/platform/users.js";
import type * as domains_platform_workspaceAi from "../domains/platform/workspaceAi.js";
import type * as domains_workspace_clients from "../domains/workspace/clients.js";
import type * as domains_workspace_projectDocumentImport from "../domains/workspace/projectDocumentImport.js";
import type * as domains_workspace_projectDocumentImportParsing from "../domains/workspace/projectDocumentImportParsing.js";
import type * as domains_workspace_projectMilestones from "../domains/workspace/projectMilestones.js";
import type * as domains_workspace_projects from "../domains/workspace/projects.js";
import type * as domains_workspace_projects_listFilters from "../domains/workspace/projects/listFilters.js";
import type * as domains_workspace_taskAssignees from "../domains/workspace/taskAssignees.js";
import type * as domains_workspace_taskComments from "../domains/workspace/taskComments.js";
import type * as domains_workspace_taskDocumentImport from "../domains/workspace/taskDocumentImport.js";
import type * as domains_workspace_taskDocumentImportParsing from "../domains/workspace/taskDocumentImportParsing.js";
import type * as domains_workspace_taskDocumentImportQueries from "../domains/workspace/taskDocumentImportQueries.js";
import type * as domains_workspace_tasks from "../domains/workspace/tasks.js";
import type * as domains_workspace_tasks_listFilters from "../domains/workspace/tasks/listFilters.js";
import type * as domains_workspace_tasks_projectCounts from "../domains/workspace/tasks/projectCounts.js";
import type * as errors from "../errors.js";
import type * as files from "../files.js";
import type * as functions from "../functions.js";
import type * as gamma from "../gamma.js";
import type * as health from "../health.js";
import type * as http from "../http.js";
import type * as httpActions from "../httpActions.js";
import type * as httpActions_metaWebhook from "../httpActions/metaWebhook.js";
import type * as inboxItems from "../inboxItems.js";
import type * as lib_artifactArchiveSchedule from "../lib/artifactArchiveSchedule.js";
import type * as lib_collaboration_readCheckpoints from "../lib/collaboration/readCheckpoints.js";
import type * as lib_collaborationPollMessage from "../lib/collaborationPollMessage.js";
import type * as lib_debugIntrospection from "../lib/debugIntrospection.js";
import type * as lib_facebookAdsAccess from "../lib/facebookAdsAccess.js";
import type * as lib_fileStorage from "../lib/fileStorage.js";
import type * as lib_functions_actionWrappers from "../lib/functions/actionWrappers.js";
import type * as lib_functions_auth from "../lib/functions/auth.js";
import type * as lib_functions_idempotency from "../lib/functions/idempotency.js";
import type * as lib_functions_mutationWrappers from "../lib/functions/mutationWrappers.js";
import type * as lib_functions_pagination from "../lib/functions/pagination.js";
import type * as lib_functions_queryWrappers from "../lib/functions/queryWrappers.js";
import type * as lib_functions_rateLimitedWrappers from "../lib/functions/rateLimitedWrappers.js";
import type * as lib_functions_response from "../lib/functions/response.js";
import type * as lib_functions_softDeleteDb from "../lib/functions/softDeleteDb.js";
import type * as lib_functions_types from "../lib/functions/types.js";
import type * as lib_functions_zodWrappers from "../lib/functions/zodWrappers.js";
import type * as lib_metaAudienceHash from "../lib/metaAudienceHash.js";
import type * as lib_metaCapiUserData from "../lib/metaCapiUserData.js";
import type * as lib_metaSha256 from "../lib/metaSha256.js";
import type * as lib_metaWebhookAuth from "../lib/metaWebhookAuth.js";
import type * as lib_r2ArtifactStore from "../lib/r2ArtifactStore.js";
import type * as lib_storageAccess from "../lib/storageAccess.js";
import type * as lib_webhookAuth from "../lib/webhookAuth.js";
import type * as meetingArchiveActions from "../meetingArchiveActions.js";
import type * as meetingArchives from "../meetingArchives.js";
import type * as meetingIntegrations from "../meetingIntegrations.js";
import type * as meetings from "../meetings.js";
import type * as messageAnalytics from "../messageAnalytics.js";
import type * as metaWebhookEvents from "../metaWebhookEvents.js";
import type * as notificationTargeting from "../notificationTargeting.js";
import type * as notifications from "../notifications.js";
import type * as onboardingStates from "../onboardingStates.js";
import type * as presentationDeck from "../presentationDeck.js";
import type * as privacyMasks from "../privacyMasks.js";
import type * as problemReports from "../problemReports.js";
import type * as projectDocumentImport from "../projectDocumentImport.js";
import type * as projectDocumentImportParsing from "../projectDocumentImportParsing.js";
import type * as projectMilestones from "../projectMilestones.js";
import type * as projects from "../projects.js";
import type * as proposalAnalytics from "../proposalAnalytics.js";
import type * as proposalArchiveActions from "../proposalArchiveActions.js";
import type * as proposalArchives from "../proposalArchives.js";
import type * as proposalGeneration from "../proposalGeneration.js";
import type * as proposalVersions from "../proposalVersions.js";
import type * as proposals from "../proposals.js";
import type * as r2 from "../r2.js";
import type * as rateLimit from "../rateLimit.js";
import type * as rateLimitApi from "../rateLimitApi.js";
import type * as schedulerAlertPreferences from "../schedulerAlertPreferences.js";
import type * as schedulerEvents from "../schedulerEvents.js";
import type * as schema_collaborationTables from "../schema/collaborationTables.js";
import type * as schema_jsonValidators from "../schema/jsonValidators.js";
import type * as schema_marketingTables from "../schema/marketingTables.js";
import type * as schema_opsTables from "../schema/opsTables.js";
import type * as schema_systemTables from "../schema/systemTables.js";
import type * as schema_workspaceTables from "../schema/workspaceTables.js";
import type * as serverCache from "../serverCache.js";
import type * as settings from "../settings.js";
import type * as socialIntegrations from "../socialIntegrations.js";
import type * as socialMetrics from "../socialMetrics.js";
import type * as socialSyncWorkerActions from "../socialSyncWorkerActions.js";
import type * as taskAssignees from "../taskAssignees.js";
import type * as taskComments from "../taskComments.js";
import type * as taskDocumentImport from "../taskDocumentImport.js";
import type * as taskDocumentImportParsing from "../taskDocumentImportParsing.js";
import type * as taskDocumentImportQueries from "../taskDocumentImportQueries.js";
import type * as tasks from "../tasks.js";
import type * as users from "../users.js";
import type * as workspaceAi from "../workspaceAi.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  activity: typeof activity;
  adSyncWorker: typeof adSyncWorker;
  adSyncWorkerActions: typeof adSyncWorkerActions;
  adminFeatures: typeof adminFeatures;
  adminFeaturesAi: typeof adminFeaturesAi;
  adminInvitations: typeof adminInvitations;
  adminMigrations: typeof adminMigrations;
  adminNotifications: typeof adminNotifications;
  adminUsage: typeof adminUsage;
  adminUserPage: typeof adminUserPage;
  adminUsers: typeof adminUsers;
  adsAdMetrics: typeof adsAdMetrics;
  adsAdSets: typeof adsAdSets;
  adsAudiences: typeof adsAudiences;
  adsAudiencesMeta: typeof adsAudiencesMeta;
  adsCampaignGroups: typeof adsCampaignGroups;
  adsCampaignInsights: typeof adsCampaignInsights;
  adsCampaigns: typeof adsCampaigns;
  adsCreatives: typeof adsCreatives;
  adsIntegrations: typeof adsIntegrations;
  adsMetaCampaigns: typeof adsMetaCampaigns;
  adsMetaEvents: typeof adsMetaEvents;
  adsMetaTools: typeof adsMetaTools;
  adsMetrics: typeof adsMetrics;
  adsTargeting: typeof adsTargeting;
  agent: typeof agent;
  agentActions: typeof agentActions;
  agentAttachments: typeof agentAttachments;
  agentConversations: typeof agentConversations;
  agentMessages: typeof agentMessages;
  alertRules: typeof alertRules;
  analyticsInsights: typeof analyticsInsights;
  analyticsIntegrations: typeof analyticsIntegrations;
  apiIdempotency: typeof apiIdempotency;
  appProxy: typeof appProxy;
  artifactArchiveBackfills: typeof artifactArchiveBackfills;
  auditLogs: typeof auditLogs;
  auth: typeof auth;
  authActions: typeof authActions;
  clientAdminTeamSync: typeof clientAdminTeamSync;
  clients: typeof clients;
  collaborationChannelAvatars: typeof collaborationChannelAvatars;
  collaborationChannels: typeof collaborationChannels;
  collaborationMessages: typeof collaborationMessages;
  collaborationTyping: typeof collaborationTyping;
  conversationRouting: typeof conversationRouting;
  creativesCopy: typeof creativesCopy;
  crons: typeof crons;
  customFormulas: typeof customFormulas;
  debug: typeof debug;
  deepseekRateLimit: typeof deepseekRateLimit;
  directMessages: typeof directMessages;
  "domains/collaboration/collaborationChannelAvatars": typeof domains_collaboration_collaborationChannelAvatars;
  "domains/collaboration/collaborationChannels": typeof domains_collaboration_collaborationChannels;
  "domains/collaboration/collaborationMessages/listing": typeof domains_collaboration_collaborationMessages_listing;
  "domains/collaboration/collaborationMessages/messageMutations": typeof domains_collaboration_collaborationMessages_messageMutations;
  "domains/collaboration/collaborationMessages/readTracking": typeof domains_collaboration_collaborationMessages_readTracking;
  "domains/collaboration/collaborationMessages/shared": typeof domains_collaboration_collaborationMessages_shared;
  "domains/collaboration/collaborationMessages/syncAndPins": typeof domains_collaboration_collaborationMessages_syncAndPins;
  "domains/collaboration/collaborationTyping": typeof domains_collaboration_collaborationTyping;
  "domains/collaboration/conversationRouting": typeof domains_collaboration_conversationRouting;
  "domains/collaboration/directMessages/conversations": typeof domains_collaboration_directMessages_conversations;
  "domains/collaboration/directMessages/messages": typeof domains_collaboration_directMessages_messages;
  "domains/collaboration/directMessages/pollsAndReactions": typeof domains_collaboration_directMessages_pollsAndReactions;
  "domains/collaboration/directMessages/shared": typeof domains_collaboration_directMessages_shared;
  "domains/collaboration/inboxItems": typeof domains_collaboration_inboxItems;
  "domains/collaboration/messageAnalytics": typeof domains_collaboration_messageAnalytics;
  "domains/marketing/adSyncWorker": typeof domains_marketing_adSyncWorker;
  "domains/marketing/adSyncWorkerActions": typeof domains_marketing_adSyncWorkerActions;
  "domains/marketing/adsAdMetrics": typeof domains_marketing_adsAdMetrics;
  "domains/marketing/adsAdSets": typeof domains_marketing_adsAdSets;
  "domains/marketing/adsAudiences": typeof domains_marketing_adsAudiences;
  "domains/marketing/adsAudiencesMeta": typeof domains_marketing_adsAudiencesMeta;
  "domains/marketing/adsCampaignGroups": typeof domains_marketing_adsCampaignGroups;
  "domains/marketing/adsCampaignInsights": typeof domains_marketing_adsCampaignInsights;
  "domains/marketing/adsCampaigns": typeof domains_marketing_adsCampaigns;
  "domains/marketing/adsCreatives": typeof domains_marketing_adsCreatives;
  "domains/marketing/adsCreativesActions/createCreative": typeof domains_marketing_adsCreativesActions_createCreative;
  "domains/marketing/adsCreativesActions/listCreatives": typeof domains_marketing_adsCreativesActions_listCreatives;
  "domains/marketing/adsCreativesActions/listMetaPageActors": typeof domains_marketing_adsCreativesActions_listMetaPageActors;
  "domains/marketing/adsCreativesActions/shared": typeof domains_marketing_adsCreativesActions_shared;
  "domains/marketing/adsCreativesActions/updateCreative": typeof domains_marketing_adsCreativesActions_updateCreative;
  "domains/marketing/adsCreativesActions/updateCreativeStatus": typeof domains_marketing_adsCreativesActions_updateCreativeStatus;
  "domains/marketing/adsCreativesActions/uploadMedia": typeof domains_marketing_adsCreativesActions_uploadMedia;
  "domains/marketing/adsIntegrations/accountInit": typeof domains_marketing_adsIntegrations_accountInit;
  "domains/marketing/adsIntegrations/credentialsStatus": typeof domains_marketing_adsIntegrations_credentialsStatus;
  "domains/marketing/adsIntegrations/discovery": typeof domains_marketing_adsIntegrations_discovery;
  "domains/marketing/adsIntegrations/metricsDeletion": typeof domains_marketing_adsIntegrations_metricsDeletion;
  "domains/marketing/adsIntegrations/queries": typeof domains_marketing_adsIntegrations_queries;
  "domains/marketing/adsIntegrations/settings": typeof domains_marketing_adsIntegrations_settings;
  "domains/marketing/adsIntegrations/shared": typeof domains_marketing_adsIntegrations_shared;
  "domains/marketing/adsIntegrations/syncJobs": typeof domains_marketing_adsIntegrations_syncJobs;
  "domains/marketing/adsMetaCampaigns": typeof domains_marketing_adsMetaCampaigns;
  "domains/marketing/adsMetaEvents": typeof domains_marketing_adsMetaEvents;
  "domains/marketing/adsMetaTools": typeof domains_marketing_adsMetaTools;
  "domains/marketing/adsMetrics": typeof domains_marketing_adsMetrics;
  "domains/marketing/adsTargeting": typeof domains_marketing_adsTargeting;
  "domains/marketing/analyticsInsights": typeof domains_marketing_analyticsInsights;
  "domains/marketing/analyticsIntegrations/accountInit": typeof domains_marketing_analyticsIntegrations_accountInit;
  "domains/marketing/analyticsIntegrations/discovery": typeof domains_marketing_analyticsIntegrations_discovery;
  "domains/marketing/analyticsIntegrations/metrics": typeof domains_marketing_analyticsIntegrations_metrics;
  "domains/marketing/analyticsIntegrations/queries": typeof domains_marketing_analyticsIntegrations_queries;
  "domains/marketing/analyticsIntegrations/settings": typeof domains_marketing_analyticsIntegrations_settings;
  "domains/marketing/analyticsIntegrations/shared": typeof domains_marketing_analyticsIntegrations_shared;
  "domains/marketing/creativesCopy": typeof domains_marketing_creativesCopy;
  "domains/marketing/customFormulas": typeof domains_marketing_customFormulas;
  "domains/marketing/metaWebhookEvents": typeof domains_marketing_metaWebhookEvents;
  "domains/marketing/socialIntegrations/discovery": typeof domains_marketing_socialIntegrations_discovery;
  "domains/marketing/socialIntegrations/metricsUpsert": typeof domains_marketing_socialIntegrations_metricsUpsert;
  "domains/marketing/socialIntegrations/queries": typeof domains_marketing_socialIntegrations_queries;
  "domains/marketing/socialIntegrations/settings": typeof domains_marketing_socialIntegrations_settings;
  "domains/marketing/socialIntegrations/syncJobs": typeof domains_marketing_socialIntegrations_syncJobs;
  "domains/marketing/socialMetrics": typeof domains_marketing_socialMetrics;
  "domains/marketing/socialSyncWorkerActions": typeof domains_marketing_socialSyncWorkerActions;
  "domains/ops/alertRules": typeof domains_ops_alertRules;
  "domains/ops/gamma": typeof domains_ops_gamma;
  "domains/ops/meetingArchiveActions": typeof domains_ops_meetingArchiveActions;
  "domains/ops/meetingArchives": typeof domains_ops_meetingArchives;
  "domains/ops/meetingIntegrations": typeof domains_ops_meetingIntegrations;
  "domains/ops/meetings": typeof domains_ops_meetings;
  "domains/ops/notificationTargeting": typeof domains_ops_notificationTargeting;
  "domains/ops/notifications": typeof domains_ops_notifications;
  "domains/ops/presentationDeck": typeof domains_ops_presentationDeck;
  "domains/ops/proposalAnalytics": typeof domains_ops_proposalAnalytics;
  "domains/ops/proposalArchiveActions": typeof domains_ops_proposalArchiveActions;
  "domains/ops/proposalArchives": typeof domains_ops_proposalArchives;
  "domains/ops/proposalGeneration": typeof domains_ops_proposalGeneration;
  "domains/ops/proposalVersions": typeof domains_ops_proposalVersions;
  "domains/ops/proposals": typeof domains_ops_proposals;
  "domains/ops/schedulerAlertPreferences": typeof domains_ops_schedulerAlertPreferences;
  "domains/platform/adminFeatures": typeof domains_platform_adminFeatures;
  "domains/platform/adminFeaturesAi": typeof domains_platform_adminFeaturesAi;
  "domains/platform/adminInvitations": typeof domains_platform_adminInvitations;
  "domains/platform/adminMigrations": typeof domains_platform_adminMigrations;
  "domains/platform/adminNotifications": typeof domains_platform_adminNotifications;
  "domains/platform/adminUsage": typeof domains_platform_adminUsage;
  "domains/platform/adminUserPage": typeof domains_platform_adminUserPage;
  "domains/platform/adminUsers": typeof domains_platform_adminUsers;
  "domains/platform/agent": typeof domains_platform_agent;
  "domains/platform/agentActions": typeof domains_platform_agentActions;
  "domains/platform/agentActions/helpers": typeof domains_platform_agentActions_helpers;
  "domains/platform/agentActions/helpers/confirmation": typeof domains_platform_agentActions_helpers_confirmation;
  "domains/platform/agentActions/helpers/context": typeof domains_platform_agentActions_helpers_context;
  "domains/platform/agentActions/helpers/dates": typeof domains_platform_agentActions_helpers_dates;
  "domains/platform/agentActions/helpers/formatting": typeof domains_platform_agentActions_helpers_formatting;
  "domains/platform/agentActions/helpers/intents": typeof domains_platform_agentActions_helpers_intents;
  "domains/platform/agentActions/helpers/intents/execute": typeof domains_platform_agentActions_helpers_intents_execute;
  "domains/platform/agentActions/helpers/intents/index": typeof domains_platform_agentActions_helpers_intents_index;
  "domains/platform/agentActions/helpers/intents/navigation": typeof domains_platform_agentActions_helpers_intents_navigation;
  "domains/platform/agentActions/helpers/intents/parsing": typeof domains_platform_agentActions_helpers_intents_parsing;
  "domains/platform/agentActions/helpers/proposalConversation": typeof domains_platform_agentActions_helpers_proposalConversation;
  "domains/platform/agentActions/helpers/proposals": typeof domains_platform_agentActions_helpers_proposals;
  "domains/platform/agentActions/helpers/values": typeof domains_platform_agentActions_helpers_values;
  "domains/platform/agentActions/operations": typeof domains_platform_agentActions_operations;
  "domains/platform/agentActions/operations/ads": typeof domains_platform_agentActions_operations_ads;
  "domains/platform/agentActions/operations/ads/index": typeof domains_platform_agentActions_operations_ads_index;
  "domains/platform/agentActions/operations/ads/reports": typeof domains_platform_agentActions_operations_ads_reports;
  "domains/platform/agentActions/operations/analyticsSummary": typeof domains_platform_agentActions_operations_analyticsSummary;
  "domains/platform/agentActions/operations/clients": typeof domains_platform_agentActions_operations_clients;
  "domains/platform/agentActions/operations/clients/index": typeof domains_platform_agentActions_operations_clients_index;
  "domains/platform/agentActions/operations/meetings/index": typeof domains_platform_agentActions_operations_meetings_index;
  "domains/platform/agentActions/operations/messaging": typeof domains_platform_agentActions_operations_messaging;
  "domains/platform/agentActions/operations/messaging/index": typeof domains_platform_agentActions_operations_messaging_index;
  "domains/platform/agentActions/operations/notifications/index": typeof domains_platform_agentActions_operations_notifications_index;
  "domains/platform/agentActions/operations/projects": typeof domains_platform_agentActions_operations_projects;
  "domains/platform/agentActions/operations/projects/index": typeof domains_platform_agentActions_operations_projects_index;
  "domains/platform/agentActions/operations/proposals": typeof domains_platform_agentActions_operations_proposals;
  "domains/platform/agentActions/operations/proposals/index": typeof domains_platform_agentActions_operations_proposals_index;
  "domains/platform/agentActions/operations/reports": typeof domains_platform_agentActions_operations_reports;
  "domains/platform/agentActions/operations/shared": typeof domains_platform_agentActions_operations_shared;
  "domains/platform/agentActions/operations/socials/index": typeof domains_platform_agentActions_operations_socials_index;
  "domains/platform/agentActions/operations/socials/socialSummary": typeof domains_platform_agentActions_operations_socials_socialSummary;
  "domains/platform/agentActions/operations/spreadsheet/builders": typeof domains_platform_agentActions_operations_spreadsheet_builders;
  "domains/platform/agentActions/operations/spreadsheet/export": typeof domains_platform_agentActions_operations_spreadsheet_export;
  "domains/platform/agentActions/operations/taskSummary": typeof domains_platform_agentActions_operations_taskSummary;
  "domains/platform/agentActions/operations/tasks": typeof domains_platform_agentActions_operations_tasks;
  "domains/platform/agentActions/operations/tasks/index": typeof domains_platform_agentActions_operations_tasks_index;
  "domains/platform/agentActions/prompting": typeof domains_platform_agentActions_prompting;
  "domains/platform/agentActions/runExecuteTurn": typeof domains_platform_agentActions_runExecuteTurn;
  "domains/platform/agentActions/types": typeof domains_platform_agentActions_types;
  "domains/platform/agentAttachments": typeof domains_platform_agentAttachments;
  "domains/platform/agentConversations": typeof domains_platform_agentConversations;
  "domains/platform/agentMessages": typeof domains_platform_agentMessages;
  "domains/platform/apiIdempotency": typeof domains_platform_apiIdempotency;
  "domains/platform/appProxy": typeof domains_platform_appProxy;
  "domains/platform/artifactArchiveBackfills": typeof domains_platform_artifactArchiveBackfills;
  "domains/platform/auditLogs": typeof domains_platform_auditLogs;
  "domains/platform/auth": typeof domains_platform_auth;
  "domains/platform/authActions": typeof domains_platform_authActions;
  "domains/platform/clientAdminTeamSync": typeof domains_platform_clientAdminTeamSync;
  "domains/platform/debug": typeof domains_platform_debug;
  "domains/platform/deepseekRateLimit": typeof domains_platform_deepseekRateLimit;
  "domains/platform/health": typeof domains_platform_health;
  "domains/platform/httpActions": typeof domains_platform_httpActions;
  "domains/platform/migrations/adMetricsCurrency": typeof domains_platform_migrations_adMetricsCurrency;
  "domains/platform/migrations/adminDiagnostics": typeof domains_platform_migrations_adminDiagnostics;
  "domains/platform/migrations/clientAdminTeam": typeof domains_platform_migrations_clientAdminTeam;
  "domains/platform/migrations/taskAssigneePools": typeof domains_platform_migrations_taskAssigneePools;
  "domains/platform/onboardingStates": typeof domains_platform_onboardingStates;
  "domains/platform/privacyMasks": typeof domains_platform_privacyMasks;
  "domains/platform/problemReports": typeof domains_platform_problemReports;
  "domains/platform/rateLimit": typeof domains_platform_rateLimit;
  "domains/platform/rateLimitApi": typeof domains_platform_rateLimitApi;
  "domains/platform/schedulerEvents": typeof domains_platform_schedulerEvents;
  "domains/platform/serverCache": typeof domains_platform_serverCache;
  "domains/platform/settings": typeof domains_platform_settings;
  "domains/platform/users": typeof domains_platform_users;
  "domains/platform/workspaceAi": typeof domains_platform_workspaceAi;
  "domains/workspace/clients": typeof domains_workspace_clients;
  "domains/workspace/projectDocumentImport": typeof domains_workspace_projectDocumentImport;
  "domains/workspace/projectDocumentImportParsing": typeof domains_workspace_projectDocumentImportParsing;
  "domains/workspace/projectMilestones": typeof domains_workspace_projectMilestones;
  "domains/workspace/projects": typeof domains_workspace_projects;
  "domains/workspace/projects/listFilters": typeof domains_workspace_projects_listFilters;
  "domains/workspace/taskAssignees": typeof domains_workspace_taskAssignees;
  "domains/workspace/taskComments": typeof domains_workspace_taskComments;
  "domains/workspace/taskDocumentImport": typeof domains_workspace_taskDocumentImport;
  "domains/workspace/taskDocumentImportParsing": typeof domains_workspace_taskDocumentImportParsing;
  "domains/workspace/taskDocumentImportQueries": typeof domains_workspace_taskDocumentImportQueries;
  "domains/workspace/tasks": typeof domains_workspace_tasks;
  "domains/workspace/tasks/listFilters": typeof domains_workspace_tasks_listFilters;
  "domains/workspace/tasks/projectCounts": typeof domains_workspace_tasks_projectCounts;
  errors: typeof errors;
  files: typeof files;
  functions: typeof functions;
  gamma: typeof gamma;
  health: typeof health;
  http: typeof http;
  httpActions: typeof httpActions;
  "httpActions/metaWebhook": typeof httpActions_metaWebhook;
  inboxItems: typeof inboxItems;
  "lib/artifactArchiveSchedule": typeof lib_artifactArchiveSchedule;
  "lib/collaboration/readCheckpoints": typeof lib_collaboration_readCheckpoints;
  "lib/collaborationPollMessage": typeof lib_collaborationPollMessage;
  "lib/debugIntrospection": typeof lib_debugIntrospection;
  "lib/facebookAdsAccess": typeof lib_facebookAdsAccess;
  "lib/fileStorage": typeof lib_fileStorage;
  "lib/functions/actionWrappers": typeof lib_functions_actionWrappers;
  "lib/functions/auth": typeof lib_functions_auth;
  "lib/functions/idempotency": typeof lib_functions_idempotency;
  "lib/functions/mutationWrappers": typeof lib_functions_mutationWrappers;
  "lib/functions/pagination": typeof lib_functions_pagination;
  "lib/functions/queryWrappers": typeof lib_functions_queryWrappers;
  "lib/functions/rateLimitedWrappers": typeof lib_functions_rateLimitedWrappers;
  "lib/functions/response": typeof lib_functions_response;
  "lib/functions/softDeleteDb": typeof lib_functions_softDeleteDb;
  "lib/functions/types": typeof lib_functions_types;
  "lib/functions/zodWrappers": typeof lib_functions_zodWrappers;
  "lib/metaAudienceHash": typeof lib_metaAudienceHash;
  "lib/metaCapiUserData": typeof lib_metaCapiUserData;
  "lib/metaSha256": typeof lib_metaSha256;
  "lib/metaWebhookAuth": typeof lib_metaWebhookAuth;
  "lib/r2ArtifactStore": typeof lib_r2ArtifactStore;
  "lib/storageAccess": typeof lib_storageAccess;
  "lib/webhookAuth": typeof lib_webhookAuth;
  meetingArchiveActions: typeof meetingArchiveActions;
  meetingArchives: typeof meetingArchives;
  meetingIntegrations: typeof meetingIntegrations;
  meetings: typeof meetings;
  messageAnalytics: typeof messageAnalytics;
  metaWebhookEvents: typeof metaWebhookEvents;
  notificationTargeting: typeof notificationTargeting;
  notifications: typeof notifications;
  onboardingStates: typeof onboardingStates;
  presentationDeck: typeof presentationDeck;
  privacyMasks: typeof privacyMasks;
  problemReports: typeof problemReports;
  projectDocumentImport: typeof projectDocumentImport;
  projectDocumentImportParsing: typeof projectDocumentImportParsing;
  projectMilestones: typeof projectMilestones;
  projects: typeof projects;
  proposalAnalytics: typeof proposalAnalytics;
  proposalArchiveActions: typeof proposalArchiveActions;
  proposalArchives: typeof proposalArchives;
  proposalGeneration: typeof proposalGeneration;
  proposalVersions: typeof proposalVersions;
  proposals: typeof proposals;
  r2: typeof r2;
  rateLimit: typeof rateLimit;
  rateLimitApi: typeof rateLimitApi;
  schedulerAlertPreferences: typeof schedulerAlertPreferences;
  schedulerEvents: typeof schedulerEvents;
  "schema/collaborationTables": typeof schema_collaborationTables;
  "schema/jsonValidators": typeof schema_jsonValidators;
  "schema/marketingTables": typeof schema_marketingTables;
  "schema/opsTables": typeof schema_opsTables;
  "schema/systemTables": typeof schema_systemTables;
  "schema/workspaceTables": typeof schema_workspaceTables;
  serverCache: typeof serverCache;
  settings: typeof settings;
  socialIntegrations: typeof socialIntegrations;
  socialMetrics: typeof socialMetrics;
  socialSyncWorkerActions: typeof socialSyncWorkerActions;
  taskAssignees: typeof taskAssignees;
  taskComments: typeof taskComments;
  taskDocumentImport: typeof taskDocumentImport;
  taskDocumentImportParsing: typeof taskDocumentImportParsing;
  taskDocumentImportQueries: typeof taskDocumentImportQueries;
  tasks: typeof tasks;
  users: typeof users;
  workspaceAi: typeof workspaceAi;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  r2: import("@convex-dev/r2/_generated/component.js").ComponentApi<"r2">;
};
