"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _dashboard_overview_page from './dashboard-overview-page.bones.json'
import _marketing_home_page from './marketing-home-page.bones.json'
import _for_you_page from './for-you-page.bones.json'
import _dashboard_analytics_page from './dashboard-analytics-page.bones.json'
import _dashboard_meetings_page from './dashboard-meetings-page.bones.json'
import _dashboard_tasks_page from './dashboard-tasks-page.bones.json'
import _dashboard_collaboration_page from './dashboard-collaboration-page.bones.json'
import _dashboard_projects_page from './dashboard-projects-page.bones.json'

registerBones({
  "dashboard-overview-page": _dashboard_overview_page,
  "marketing-home-page": _marketing_home_page,
  "for-you-page": _for_you_page,
  "dashboard-analytics-page": _dashboard_analytics_page,
  "dashboard-meetings-page": _dashboard_meetings_page,
  "dashboard-tasks-page": _dashboard_tasks_page,
  "dashboard-collaboration-page": _dashboard_collaboration_page,
  "dashboard-projects-page": _dashboard_projects_page,
})
