"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _dashboard_ads_page from './dashboard-ads-page.bones.json'
import _dashboard_clients_page from './dashboard-clients-page.bones.json'
import _dashboard_collaboration_page from './dashboard-collaboration-page.bones.json'
import _dashboard_projects_page from './dashboard-projects-page.bones.json'

registerBones({
  "dashboard-ads-page": _dashboard_ads_page,
  "dashboard-clients-page": _dashboard_clients_page,
  "dashboard-collaboration-page": _dashboard_collaboration_page,
  "dashboard-projects-page": _dashboard_projects_page,
})
