/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ManifestWebmanifestRouteImport } from './routes/manifest.webmanifest'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedForYouRouteImport } from './routes/_authed/for-you'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiProxyFileRouteImport } from './routes/api/proxy/file'
import { Route as ApiMeetingsTranscriptRouteImport } from './routes/api/meetings/transcript'
import { Route as ApiMeetingsScheduleRouteImport } from './routes/api/meetings/schedule'
import { Route as ApiMeetingsRescheduleRouteImport } from './routes/api/meetings/reschedule'
import { Route as ApiMeetingsQuickRouteImport } from './routes/api/meetings/quick'
import { Route as ApiMeetingsCancelRouteImport } from './routes/api/meetings/cancel'
import { Route as ApiIntegrationsWorkerRouteImport } from './routes/api/integrations/worker'
import { Route as ApiIntegrationsScheduleRouteImport } from './routes/api/integrations/schedule'
import { Route as ApiIntegrationsProcessRouteImport } from './routes/api/integrations/process'
import { Route as ApiIntegrationsManualSyncRouteImport } from './routes/api/integrations/manual-sync'
import { Route as ApiIntegrationsCronRouteImport } from './routes/api/integrations/cron'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiFilesProxyRouteImport } from './routes/api/files/proxy'
import { Route as ApiDebugClientsRouteImport } from './routes/api/debug/clients'
import { Route as ApiDashboardClientSummaryRouteImport } from './routes/api/dashboard/client-summary'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDashboardTasksRouteImport } from './routes/_authed/dashboard/tasks'
import { Route as AuthedDashboardSocialsRouteImport } from './routes/_authed/dashboard/socials'
import { Route as AuthedDashboardProjectsRouteImport } from './routes/_authed/dashboard/projects'
import { Route as AuthedDashboardNotificationsRouteImport } from './routes/_authed/dashboard/notifications'
import { Route as AuthedDashboardMeetingsRouteImport } from './routes/_authed/dashboard/meetings'
import { Route as AuthedDashboardCollaborationRouteImport } from './routes/_authed/dashboard/collaboration'
import { Route as AuthedDashboardClientsRouteImport } from './routes/_authed/dashboard/clients'
import { Route as AuthedDashboardAnalyticsRouteImport } from './routes/_authed/dashboard/analytics'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminTeamRouteImport } from './routes/_authed/admin/team'
import { Route as AuthedAdminIssuesRouteImport } from './routes/_authed/admin/issues'
import { Route as AuthedAdminHealthRouteImport } from './routes/_authed/admin/health'
import { Route as AuthedAdminFeaturesRouteImport } from './routes/_authed/admin/features'
import { Route as AuthedAdminClientsRouteImport } from './routes/_authed/admin/clients'
import { Route as AuthedDashboardSettingsIndexRouteImport } from './routes/_authed/dashboard/settings/index'
import { Route as AuthedDashboardProposalsIndexRouteImport } from './routes/_authed/dashboard/proposals/index'
import { Route as AuthedDashboardAdsIndexRouteImport } from './routes/_authed/dashboard/ads/index'
import { Route as ApiMeetingsLivekitTokenRouteImport } from './routes/api/meetings/livekit/token'
import { Route as ApiIntegrationsGoogleWorkspaceEventsRouteImport } from './routes/api/integrations/google-workspace/events'
import { Route as ApiIntegrationsEmailSendRouteImport } from './routes/api/integrations/email/send'
import { Route as ApiAnalyticsGoogleAnalyticsSyncRouteImport } from './routes/api/analytics/google-analytics/sync'
import { Route as AuthedDashboardSettingsIntegrationsRouteImport } from './routes/_authed/dashboard/settings/integrations'
import { Route as AuthedDashboardProposalsViewerRouteImport } from './routes/_authed/dashboard/proposals/viewer'
import { Route as AuthedDashboardProposalsAnalyticsRouteImport } from './routes/_authed/dashboard/proposals/analytics'
import { Route as ApiIntegrationsTiktokOauthUrlRouteImport } from './routes/api/integrations/tiktok/oauth/url'
import { Route as ApiIntegrationsTiktokOauthCallbackRouteImport } from './routes/api/integrations/tiktok/oauth/callback'
import { Route as ApiIntegrationsMetaOauthUrlRouteImport } from './routes/api/integrations/meta/oauth/url'
import { Route as ApiIntegrationsMetaOauthCallbackRouteImport } from './routes/api/integrations/meta/oauth/callback'
import { Route as ApiIntegrationsLinkedinOauthUrlRouteImport } from './routes/api/integrations/linkedin/oauth/url'
import { Route as ApiIntegrationsLinkedinOauthCallbackRouteImport } from './routes/api/integrations/linkedin/oauth/callback'
import { Route as ApiIntegrationsGoogleOauthUrlRouteImport } from './routes/api/integrations/google/oauth/url'
import { Route as ApiIntegrationsGoogleOauthCallbackRouteImport } from './routes/api/integrations/google/oauth/callback'
import { Route as ApiIntegrationsGoogleWorkspaceOauthUrlRouteImport } from './routes/api/integrations/google-workspace/oauth/url'
import { Route as ApiIntegrationsGoogleWorkspaceOauthCallbackRouteImport } from './routes/api/integrations/google-workspace/oauth/callback'
import { Route as ApiIntegrationsGoogleAnalyticsOauthStartRouteImport } from './routes/api/integrations/google-analytics/oauth/start'
import { Route as ApiIntegrationsGoogleAnalyticsOauthCallbackRouteImport } from './routes/api/integrations/google-analytics/oauth/callback'
import { Route as AuthedDashboardProposalsProposalIdDeckRouteImport } from './routes/_authed/dashboard/proposals/$proposalId/deck'
import { Route as AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteImport } from './routes/_authed/dashboard/ads/campaigns/$providerId/$campaignId'
import { Route as AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRouteImport } from './routes/_authed/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const ManifestWebmanifestRoute = ManifestWebmanifestRouteImport.update({
  id: '/manifest/webmanifest',
  path: '/manifest/webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedForYouRoute = AuthedForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const ApiProxyFileRoute = ApiProxyFileRouteImport.update({
  id: '/api/proxy/file',
  path: '/api/proxy/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsTranscriptRoute = ApiMeetingsTranscriptRouteImport.update({
  id: '/api/meetings/transcript',
  path: '/api/meetings/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsScheduleRoute = ApiMeetingsScheduleRouteImport.update({
  id: '/api/meetings/schedule',
  path: '/api/meetings/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRescheduleRoute = ApiMeetingsRescheduleRouteImport.update({
  id: '/api/meetings/reschedule',
  path: '/api/meetings/reschedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsQuickRoute = ApiMeetingsQuickRouteImport.update({
  id: '/api/meetings/quick',
  path: '/api/meetings/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsCancelRoute = ApiMeetingsCancelRouteImport.update({
  id: '/api/meetings/cancel',
  path: '/api/meetings/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsWorkerRoute = ApiIntegrationsWorkerRouteImport.update({
  id: '/api/integrations/worker',
  path: '/api/integrations/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsScheduleRoute = ApiIntegrationsScheduleRouteImport.update({
  id: '/api/integrations/schedule',
  path: '/api/integrations/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsProcessRoute = ApiIntegrationsProcessRouteImport.update({
  id: '/api/integrations/process',
  path: '/api/integrations/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsManualSyncRoute =
  ApiIntegrationsManualSyncRouteImport.update({
    id: '/api/integrations/manual-sync',
    path: '/api/integrations/manual-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsCronRoute = ApiIntegrationsCronRouteImport.update({
  id: '/api/integrations/cron',
  path: '/api/integrations/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiFilesProxyRoute = ApiFilesProxyRouteImport.update({
  id: '/api/files/proxy',
  path: '/api/files/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugClientsRoute = ApiDebugClientsRouteImport.update({
  id: '/api/debug/clients',
  path: '/api/debug/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardClientSummaryRoute =
  ApiDashboardClientSummaryRouteImport.update({
    id: '/api/dashboard/client-summary',
    path: '/api/dashboard/client-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardTasksRoute = AuthedDashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardSocialsRoute = AuthedDashboardSocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardProjectsRoute = AuthedDashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardNotificationsRoute =
  AuthedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMeetingsRoute = AuthedDashboardMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardCollaborationRoute =
  AuthedDashboardCollaborationRouteImport.update({
    id: '/collaboration',
    path: '/collaboration',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardClientsRoute = AuthedDashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardAnalyticsRoute =
  AuthedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminTeamRoute = AuthedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminIssuesRoute = AuthedAdminIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminHealthRoute = AuthedAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminFeaturesRoute = AuthedAdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminClientsRoute = AuthedAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedDashboardSettingsIndexRoute =
  AuthedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardProposalsIndexRoute =
  AuthedDashboardProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardAdsIndexRoute = AuthedDashboardAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const ApiMeetingsLivekitTokenRoute = ApiMeetingsLivekitTokenRouteImport.update({
  id: '/api/meetings/livekit/token',
  path: '/api/meetings/livekit/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsGoogleWorkspaceEventsRoute =
  ApiIntegrationsGoogleWorkspaceEventsRouteImport.update({
    id: '/api/integrations/google-workspace/events',
    path: '/api/integrations/google-workspace/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsEmailSendRoute =
  ApiIntegrationsEmailSendRouteImport.update({
    id: '/api/integrations/email/send',
    path: '/api/integrations/email/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsGoogleAnalyticsSyncRoute =
  ApiAnalyticsGoogleAnalyticsSyncRouteImport.update({
    id: '/api/analytics/google-analytics/sync',
    path: '/api/analytics/google-analytics/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedDashboardSettingsIntegrationsRoute =
  AuthedDashboardSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardProposalsViewerRoute =
  AuthedDashboardProposalsViewerRouteImport.update({
    id: '/proposals/viewer',
    path: '/proposals/viewer',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardProposalsAnalyticsRoute =
  AuthedDashboardProposalsAnalyticsRouteImport.update({
    id: '/proposals/analytics',
    path: '/proposals/analytics',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const ApiIntegrationsTiktokOauthUrlRoute =
  ApiIntegrationsTiktokOauthUrlRouteImport.update({
    id: '/api/integrations/tiktok/oauth/url',
    path: '/api/integrations/tiktok/oauth/url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTiktokOauthCallbackRoute =
  ApiIntegrationsTiktokOauthCallbackRouteImport.update({
    id: '/api/integrations/tiktok/oauth/callback',
    path: '/api/integrations/tiktok/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaOauthUrlRoute =
  ApiIntegrationsMetaOauthUrlRouteImport.update({
    id: '/api/integrations/meta/oauth/url',
    path: '/api/integrations/meta/oauth/url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaOauthCallbackRoute =
  ApiIntegrationsMetaOauthCallbackRouteImport.update({
    id: '/api/integrations/meta/oauth/callback',
    path: '/api/integrations/meta/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsLinkedinOauthUrlRoute =
  ApiIntegrationsLinkedinOauthUrlRouteImport.update({
    id: '/api/integrations/linkedin/oauth/url',
    path: '/api/integrations/linkedin/oauth/url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsLinkedinOauthCallbackRoute =
  ApiIntegrationsLinkedinOauthCallbackRouteImport.update({
    id: '/api/integrations/linkedin/oauth/callback',
    path: '/api/integrations/linkedin/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleOauthUrlRoute =
  ApiIntegrationsGoogleOauthUrlRouteImport.update({
    id: '/api/integrations/google/oauth/url',
    path: '/api/integrations/google/oauth/url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleOauthCallbackRoute =
  ApiIntegrationsGoogleOauthCallbackRouteImport.update({
    id: '/api/integrations/google/oauth/callback',
    path: '/api/integrations/google/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceOauthUrlRoute =
  ApiIntegrationsGoogleWorkspaceOauthUrlRouteImport.update({
    id: '/api/integrations/google-workspace/oauth/url',
    path: '/api/integrations/google-workspace/oauth/url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceOauthCallbackRoute =
  ApiIntegrationsGoogleWorkspaceOauthCallbackRouteImport.update({
    id: '/api/integrations/google-workspace/oauth/callback',
    path: '/api/integrations/google-workspace/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleAnalyticsOauthStartRoute =
  ApiIntegrationsGoogleAnalyticsOauthStartRouteImport.update({
    id: '/api/integrations/google-analytics/oauth/start',
    path: '/api/integrations/google-analytics/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleAnalyticsOauthCallbackRoute =
  ApiIntegrationsGoogleAnalyticsOauthCallbackRouteImport.update({
    id: '/api/integrations/google-analytics/oauth/callback',
    path: '/api/integrations/google-analytics/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedDashboardProposalsProposalIdDeckRoute =
  AuthedDashboardProposalsProposalIdDeckRouteImport.update({
    id: '/proposals/$proposalId/deck',
    path: '/proposals/$proposalId/deck',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardAdsCampaignsProviderIdCampaignIdRoute =
  AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteImport.update({
    id: '/ads/campaigns/$providerId/$campaignId',
    path: '/ads/campaigns/$providerId/$campaignId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute =
  AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRouteImport.update(
    {
      id: '/creative/$creativeId',
      path: '/creative/$creativeId',
      getParentRoute: () =>
        AuthedDashboardAdsCampaignsProviderIdCampaignIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/for-you': typeof AuthedForYouRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/manifest/webmanifest': typeof ManifestWebmanifestRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/clients': typeof AuthedAdminClientsRoute
  '/admin/features': typeof AuthedAdminFeaturesRoute
  '/admin/health': typeof AuthedAdminHealthRoute
  '/admin/issues': typeof AuthedAdminIssuesRoute
  '/admin/team': typeof AuthedAdminTeamRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/dashboard/analytics': typeof AuthedDashboardAnalyticsRoute
  '/dashboard/clients': typeof AuthedDashboardClientsRoute
  '/dashboard/collaboration': typeof AuthedDashboardCollaborationRoute
  '/dashboard/meetings': typeof AuthedDashboardMeetingsRoute
  '/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/dashboard/projects': typeof AuthedDashboardProjectsRoute
  '/dashboard/socials': typeof AuthedDashboardSocialsRoute
  '/dashboard/tasks': typeof AuthedDashboardTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/client-summary': typeof ApiDashboardClientSummaryRoute
  '/api/debug/clients': typeof ApiDebugClientsRoute
  '/api/files/proxy': typeof ApiFilesProxyRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/integrations/cron': typeof ApiIntegrationsCronRoute
  '/api/integrations/manual-sync': typeof ApiIntegrationsManualSyncRoute
  '/api/integrations/process': typeof ApiIntegrationsProcessRoute
  '/api/integrations/schedule': typeof ApiIntegrationsScheduleRoute
  '/api/integrations/worker': typeof ApiIntegrationsWorkerRoute
  '/api/meetings/cancel': typeof ApiMeetingsCancelRoute
  '/api/meetings/quick': typeof ApiMeetingsQuickRoute
  '/api/meetings/reschedule': typeof ApiMeetingsRescheduleRoute
  '/api/meetings/schedule': typeof ApiMeetingsScheduleRoute
  '/api/meetings/transcript': typeof ApiMeetingsTranscriptRoute
  '/api/proxy/file': typeof ApiProxyFileRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/proposals/analytics': typeof AuthedDashboardProposalsAnalyticsRoute
  '/dashboard/proposals/viewer': typeof AuthedDashboardProposalsViewerRoute
  '/dashboard/settings/integrations': typeof AuthedDashboardSettingsIntegrationsRoute
  '/api/analytics/google-analytics/sync': typeof ApiAnalyticsGoogleAnalyticsSyncRoute
  '/api/integrations/email/send': typeof ApiIntegrationsEmailSendRoute
  '/api/integrations/google-workspace/events': typeof ApiIntegrationsGoogleWorkspaceEventsRoute
  '/api/meetings/livekit/token': typeof ApiMeetingsLivekitTokenRoute
  '/dashboard/ads/': typeof AuthedDashboardAdsIndexRoute
  '/dashboard/proposals/': typeof AuthedDashboardProposalsIndexRoute
  '/dashboard/settings/': typeof AuthedDashboardSettingsIndexRoute
  '/dashboard/proposals/$proposalId/deck': typeof AuthedDashboardProposalsProposalIdDeckRoute
  '/api/integrations/google-analytics/oauth/callback': typeof ApiIntegrationsGoogleAnalyticsOauthCallbackRoute
  '/api/integrations/google-analytics/oauth/start': typeof ApiIntegrationsGoogleAnalyticsOauthStartRoute
  '/api/integrations/google-workspace/oauth/callback': typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
  '/api/integrations/google-workspace/oauth/url': typeof ApiIntegrationsGoogleWorkspaceOauthUrlRoute
  '/api/integrations/google/oauth/callback': typeof ApiIntegrationsGoogleOauthCallbackRoute
  '/api/integrations/google/oauth/url': typeof ApiIntegrationsGoogleOauthUrlRoute
  '/api/integrations/linkedin/oauth/callback': typeof ApiIntegrationsLinkedinOauthCallbackRoute
  '/api/integrations/linkedin/oauth/url': typeof ApiIntegrationsLinkedinOauthUrlRoute
  '/api/integrations/meta/oauth/callback': typeof ApiIntegrationsMetaOauthCallbackRoute
  '/api/integrations/meta/oauth/url': typeof ApiIntegrationsMetaOauthUrlRoute
  '/api/integrations/tiktok/oauth/callback': typeof ApiIntegrationsTiktokOauthCallbackRoute
  '/api/integrations/tiktok/oauth/url': typeof ApiIntegrationsTiktokOauthUrlRoute
  '/dashboard/ads/campaigns/$providerId/$campaignId': typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteWithChildren
  '/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId': typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/for-you': typeof AuthedForYouRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/manifest/webmanifest': typeof ManifestWebmanifestRoute
  '/auth': typeof AuthIndexRoute
  '/admin/clients': typeof AuthedAdminClientsRoute
  '/admin/features': typeof AuthedAdminFeaturesRoute
  '/admin/health': typeof AuthedAdminHealthRoute
  '/admin/issues': typeof AuthedAdminIssuesRoute
  '/admin/team': typeof AuthedAdminTeamRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/dashboard/analytics': typeof AuthedDashboardAnalyticsRoute
  '/dashboard/clients': typeof AuthedDashboardClientsRoute
  '/dashboard/collaboration': typeof AuthedDashboardCollaborationRoute
  '/dashboard/meetings': typeof AuthedDashboardMeetingsRoute
  '/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/dashboard/projects': typeof AuthedDashboardProjectsRoute
  '/dashboard/socials': typeof AuthedDashboardSocialsRoute
  '/dashboard/tasks': typeof AuthedDashboardTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/client-summary': typeof ApiDashboardClientSummaryRoute
  '/api/debug/clients': typeof ApiDebugClientsRoute
  '/api/files/proxy': typeof ApiFilesProxyRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/integrations/cron': typeof ApiIntegrationsCronRoute
  '/api/integrations/manual-sync': typeof ApiIntegrationsManualSyncRoute
  '/api/integrations/process': typeof ApiIntegrationsProcessRoute
  '/api/integrations/schedule': typeof ApiIntegrationsScheduleRoute
  '/api/integrations/worker': typeof ApiIntegrationsWorkerRoute
  '/api/meetings/cancel': typeof ApiMeetingsCancelRoute
  '/api/meetings/quick': typeof ApiMeetingsQuickRoute
  '/api/meetings/reschedule': typeof ApiMeetingsRescheduleRoute
  '/api/meetings/schedule': typeof ApiMeetingsScheduleRoute
  '/api/meetings/transcript': typeof ApiMeetingsTranscriptRoute
  '/api/proxy/file': typeof ApiProxyFileRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/proposals/analytics': typeof AuthedDashboardProposalsAnalyticsRoute
  '/dashboard/proposals/viewer': typeof AuthedDashboardProposalsViewerRoute
  '/dashboard/settings/integrations': typeof AuthedDashboardSettingsIntegrationsRoute
  '/api/analytics/google-analytics/sync': typeof ApiAnalyticsGoogleAnalyticsSyncRoute
  '/api/integrations/email/send': typeof ApiIntegrationsEmailSendRoute
  '/api/integrations/google-workspace/events': typeof ApiIntegrationsGoogleWorkspaceEventsRoute
  '/api/meetings/livekit/token': typeof ApiMeetingsLivekitTokenRoute
  '/dashboard/ads': typeof AuthedDashboardAdsIndexRoute
  '/dashboard/proposals': typeof AuthedDashboardProposalsIndexRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsIndexRoute
  '/dashboard/proposals/$proposalId/deck': typeof AuthedDashboardProposalsProposalIdDeckRoute
  '/api/integrations/google-analytics/oauth/callback': typeof ApiIntegrationsGoogleAnalyticsOauthCallbackRoute
  '/api/integrations/google-analytics/oauth/start': typeof ApiIntegrationsGoogleAnalyticsOauthStartRoute
  '/api/integrations/google-workspace/oauth/callback': typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
  '/api/integrations/google-workspace/oauth/url': typeof ApiIntegrationsGoogleWorkspaceOauthUrlRoute
  '/api/integrations/google/oauth/callback': typeof ApiIntegrationsGoogleOauthCallbackRoute
  '/api/integrations/google/oauth/url': typeof ApiIntegrationsGoogleOauthUrlRoute
  '/api/integrations/linkedin/oauth/callback': typeof ApiIntegrationsLinkedinOauthCallbackRoute
  '/api/integrations/linkedin/oauth/url': typeof ApiIntegrationsLinkedinOauthUrlRoute
  '/api/integrations/meta/oauth/callback': typeof ApiIntegrationsMetaOauthCallbackRoute
  '/api/integrations/meta/oauth/url': typeof ApiIntegrationsMetaOauthUrlRoute
  '/api/integrations/tiktok/oauth/callback': typeof ApiIntegrationsTiktokOauthCallbackRoute
  '/api/integrations/tiktok/oauth/url': typeof ApiIntegrationsTiktokOauthUrlRoute
  '/dashboard/ads/campaigns/$providerId/$campaignId': typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteWithChildren
  '/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId': typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/_authed/for-you': typeof AuthedForYouRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/manifest/webmanifest': typeof ManifestWebmanifestRoute
  '/auth/': typeof AuthIndexRoute
  '/_authed/admin/clients': typeof AuthedAdminClientsRoute
  '/_authed/admin/features': typeof AuthedAdminFeaturesRoute
  '/_authed/admin/health': typeof AuthedAdminHealthRoute
  '/_authed/admin/issues': typeof AuthedAdminIssuesRoute
  '/_authed/admin/team': typeof AuthedAdminTeamRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/dashboard/analytics': typeof AuthedDashboardAnalyticsRoute
  '/_authed/dashboard/clients': typeof AuthedDashboardClientsRoute
  '/_authed/dashboard/collaboration': typeof AuthedDashboardCollaborationRoute
  '/_authed/dashboard/meetings': typeof AuthedDashboardMeetingsRoute
  '/_authed/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/_authed/dashboard/projects': typeof AuthedDashboardProjectsRoute
  '/_authed/dashboard/socials': typeof AuthedDashboardSocialsRoute
  '/_authed/dashboard/tasks': typeof AuthedDashboardTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/client-summary': typeof ApiDashboardClientSummaryRoute
  '/api/debug/clients': typeof ApiDebugClientsRoute
  '/api/files/proxy': typeof ApiFilesProxyRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/integrations/cron': typeof ApiIntegrationsCronRoute
  '/api/integrations/manual-sync': typeof ApiIntegrationsManualSyncRoute
  '/api/integrations/process': typeof ApiIntegrationsProcessRoute
  '/api/integrations/schedule': typeof ApiIntegrationsScheduleRoute
  '/api/integrations/worker': typeof ApiIntegrationsWorkerRoute
  '/api/meetings/cancel': typeof ApiMeetingsCancelRoute
  '/api/meetings/quick': typeof ApiMeetingsQuickRoute
  '/api/meetings/reschedule': typeof ApiMeetingsRescheduleRoute
  '/api/meetings/schedule': typeof ApiMeetingsScheduleRoute
  '/api/meetings/transcript': typeof ApiMeetingsTranscriptRoute
  '/api/proxy/file': typeof ApiProxyFileRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/proposals/analytics': typeof AuthedDashboardProposalsAnalyticsRoute
  '/_authed/dashboard/proposals/viewer': typeof AuthedDashboardProposalsViewerRoute
  '/_authed/dashboard/settings/integrations': typeof AuthedDashboardSettingsIntegrationsRoute
  '/api/analytics/google-analytics/sync': typeof ApiAnalyticsGoogleAnalyticsSyncRoute
  '/api/integrations/email/send': typeof ApiIntegrationsEmailSendRoute
  '/api/integrations/google-workspace/events': typeof ApiIntegrationsGoogleWorkspaceEventsRoute
  '/api/meetings/livekit/token': typeof ApiMeetingsLivekitTokenRoute
  '/_authed/dashboard/ads/': typeof AuthedDashboardAdsIndexRoute
  '/_authed/dashboard/proposals/': typeof AuthedDashboardProposalsIndexRoute
  '/_authed/dashboard/settings/': typeof AuthedDashboardSettingsIndexRoute
  '/_authed/dashboard/proposals/$proposalId/deck': typeof AuthedDashboardProposalsProposalIdDeckRoute
  '/api/integrations/google-analytics/oauth/callback': typeof ApiIntegrationsGoogleAnalyticsOauthCallbackRoute
  '/api/integrations/google-analytics/oauth/start': typeof ApiIntegrationsGoogleAnalyticsOauthStartRoute
  '/api/integrations/google-workspace/oauth/callback': typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
  '/api/integrations/google-workspace/oauth/url': typeof ApiIntegrationsGoogleWorkspaceOauthUrlRoute
  '/api/integrations/google/oauth/callback': typeof ApiIntegrationsGoogleOauthCallbackRoute
  '/api/integrations/google/oauth/url': typeof ApiIntegrationsGoogleOauthUrlRoute
  '/api/integrations/linkedin/oauth/callback': typeof ApiIntegrationsLinkedinOauthCallbackRoute
  '/api/integrations/linkedin/oauth/url': typeof ApiIntegrationsLinkedinOauthUrlRoute
  '/api/integrations/meta/oauth/callback': typeof ApiIntegrationsMetaOauthCallbackRoute
  '/api/integrations/meta/oauth/url': typeof ApiIntegrationsMetaOauthUrlRoute
  '/api/integrations/tiktok/oauth/callback': typeof ApiIntegrationsTiktokOauthCallbackRoute
  '/api/integrations/tiktok/oauth/url': typeof ApiIntegrationsTiktokOauthUrlRoute
  '/_authed/dashboard/ads/campaigns/$providerId/$campaignId': typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteWithChildren
  '/_authed/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId': typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending-approval'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/for-you'
    | '/settings'
    | '/api/health'
    | '/auth/forgot'
    | '/auth/reset'
    | '/manifest/webmanifest'
    | '/auth/'
    | '/admin/clients'
    | '/admin/features'
    | '/admin/health'
    | '/admin/issues'
    | '/admin/team'
    | '/admin/users'
    | '/dashboard/analytics'
    | '/dashboard/clients'
    | '/dashboard/collaboration'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/projects'
    | '/dashboard/socials'
    | '/dashboard/tasks'
    | '/api/auth/$'
    | '/api/dashboard/client-summary'
    | '/api/debug/clients'
    | '/api/files/proxy'
    | '/api/health/ready'
    | '/api/integrations/cron'
    | '/api/integrations/manual-sync'
    | '/api/integrations/process'
    | '/api/integrations/schedule'
    | '/api/integrations/worker'
    | '/api/meetings/cancel'
    | '/api/meetings/quick'
    | '/api/meetings/reschedule'
    | '/api/meetings/schedule'
    | '/api/meetings/transcript'
    | '/api/proxy/file'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/proposals/analytics'
    | '/dashboard/proposals/viewer'
    | '/dashboard/settings/integrations'
    | '/api/analytics/google-analytics/sync'
    | '/api/integrations/email/send'
    | '/api/integrations/google-workspace/events'
    | '/api/meetings/livekit/token'
    | '/dashboard/ads/'
    | '/dashboard/proposals/'
    | '/dashboard/settings/'
    | '/dashboard/proposals/$proposalId/deck'
    | '/api/integrations/google-analytics/oauth/callback'
    | '/api/integrations/google-analytics/oauth/start'
    | '/api/integrations/google-workspace/oauth/callback'
    | '/api/integrations/google-workspace/oauth/url'
    | '/api/integrations/google/oauth/callback'
    | '/api/integrations/google/oauth/url'
    | '/api/integrations/linkedin/oauth/callback'
    | '/api/integrations/linkedin/oauth/url'
    | '/api/integrations/meta/oauth/callback'
    | '/api/integrations/meta/oauth/url'
    | '/api/integrations/tiktok/oauth/callback'
    | '/api/integrations/tiktok/oauth/url'
    | '/dashboard/ads/campaigns/$providerId/$campaignId'
    | '/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pending-approval'
    | '/privacy'
    | '/terms'
    | '/for-you'
    | '/settings'
    | '/api/health'
    | '/auth/forgot'
    | '/auth/reset'
    | '/manifest/webmanifest'
    | '/auth'
    | '/admin/clients'
    | '/admin/features'
    | '/admin/health'
    | '/admin/issues'
    | '/admin/team'
    | '/admin/users'
    | '/dashboard/analytics'
    | '/dashboard/clients'
    | '/dashboard/collaboration'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/projects'
    | '/dashboard/socials'
    | '/dashboard/tasks'
    | '/api/auth/$'
    | '/api/dashboard/client-summary'
    | '/api/debug/clients'
    | '/api/files/proxy'
    | '/api/health/ready'
    | '/api/integrations/cron'
    | '/api/integrations/manual-sync'
    | '/api/integrations/process'
    | '/api/integrations/schedule'
    | '/api/integrations/worker'
    | '/api/meetings/cancel'
    | '/api/meetings/quick'
    | '/api/meetings/reschedule'
    | '/api/meetings/schedule'
    | '/api/meetings/transcript'
    | '/api/proxy/file'
    | '/admin'
    | '/dashboard'
    | '/dashboard/proposals/analytics'
    | '/dashboard/proposals/viewer'
    | '/dashboard/settings/integrations'
    | '/api/analytics/google-analytics/sync'
    | '/api/integrations/email/send'
    | '/api/integrations/google-workspace/events'
    | '/api/meetings/livekit/token'
    | '/dashboard/ads'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/proposals/$proposalId/deck'
    | '/api/integrations/google-analytics/oauth/callback'
    | '/api/integrations/google-analytics/oauth/start'
    | '/api/integrations/google-workspace/oauth/callback'
    | '/api/integrations/google-workspace/oauth/url'
    | '/api/integrations/google/oauth/callback'
    | '/api/integrations/google/oauth/url'
    | '/api/integrations/linkedin/oauth/callback'
    | '/api/integrations/linkedin/oauth/url'
    | '/api/integrations/meta/oauth/callback'
    | '/api/integrations/meta/oauth/url'
    | '/api/integrations/tiktok/oauth/callback'
    | '/api/integrations/tiktok/oauth/url'
    | '/dashboard/ads/campaigns/$providerId/$campaignId'
    | '/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/pending-approval'
    | '/privacy'
    | '/terms'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/_authed/for-you'
    | '/_authed/settings'
    | '/api/health'
    | '/auth/forgot'
    | '/auth/reset'
    | '/manifest/webmanifest'
    | '/auth/'
    | '/_authed/admin/clients'
    | '/_authed/admin/features'
    | '/_authed/admin/health'
    | '/_authed/admin/issues'
    | '/_authed/admin/team'
    | '/_authed/admin/users'
    | '/_authed/dashboard/analytics'
    | '/_authed/dashboard/clients'
    | '/_authed/dashboard/collaboration'
    | '/_authed/dashboard/meetings'
    | '/_authed/dashboard/notifications'
    | '/_authed/dashboard/projects'
    | '/_authed/dashboard/socials'
    | '/_authed/dashboard/tasks'
    | '/api/auth/$'
    | '/api/dashboard/client-summary'
    | '/api/debug/clients'
    | '/api/files/proxy'
    | '/api/health/ready'
    | '/api/integrations/cron'
    | '/api/integrations/manual-sync'
    | '/api/integrations/process'
    | '/api/integrations/schedule'
    | '/api/integrations/worker'
    | '/api/meetings/cancel'
    | '/api/meetings/quick'
    | '/api/meetings/reschedule'
    | '/api/meetings/schedule'
    | '/api/meetings/transcript'
    | '/api/proxy/file'
    | '/_authed/admin/'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/proposals/analytics'
    | '/_authed/dashboard/proposals/viewer'
    | '/_authed/dashboard/settings/integrations'
    | '/api/analytics/google-analytics/sync'
    | '/api/integrations/email/send'
    | '/api/integrations/google-workspace/events'
    | '/api/meetings/livekit/token'
    | '/_authed/dashboard/ads/'
    | '/_authed/dashboard/proposals/'
    | '/_authed/dashboard/settings/'
    | '/_authed/dashboard/proposals/$proposalId/deck'
    | '/api/integrations/google-analytics/oauth/callback'
    | '/api/integrations/google-analytics/oauth/start'
    | '/api/integrations/google-workspace/oauth/callback'
    | '/api/integrations/google-workspace/oauth/url'
    | '/api/integrations/google/oauth/callback'
    | '/api/integrations/google/oauth/url'
    | '/api/integrations/linkedin/oauth/callback'
    | '/api/integrations/linkedin/oauth/url'
    | '/api/integrations/meta/oauth/callback'
    | '/api/integrations/meta/oauth/url'
    | '/api/integrations/tiktok/oauth/callback'
    | '/api/integrations/tiktok/oauth/url'
    | '/_authed/dashboard/ads/campaigns/$providerId/$campaignId'
    | '/_authed/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PendingApprovalRoute: typeof PendingApprovalRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ManifestWebmanifestRoute: typeof ManifestWebmanifestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDashboardClientSummaryRoute: typeof ApiDashboardClientSummaryRoute
  ApiDebugClientsRoute: typeof ApiDebugClientsRoute
  ApiFilesProxyRoute: typeof ApiFilesProxyRoute
  ApiIntegrationsCronRoute: typeof ApiIntegrationsCronRoute
  ApiIntegrationsManualSyncRoute: typeof ApiIntegrationsManualSyncRoute
  ApiIntegrationsProcessRoute: typeof ApiIntegrationsProcessRoute
  ApiIntegrationsScheduleRoute: typeof ApiIntegrationsScheduleRoute
  ApiIntegrationsWorkerRoute: typeof ApiIntegrationsWorkerRoute
  ApiMeetingsCancelRoute: typeof ApiMeetingsCancelRoute
  ApiMeetingsQuickRoute: typeof ApiMeetingsQuickRoute
  ApiMeetingsRescheduleRoute: typeof ApiMeetingsRescheduleRoute
  ApiMeetingsScheduleRoute: typeof ApiMeetingsScheduleRoute
  ApiMeetingsTranscriptRoute: typeof ApiMeetingsTranscriptRoute
  ApiProxyFileRoute: typeof ApiProxyFileRoute
  ApiAnalyticsGoogleAnalyticsSyncRoute: typeof ApiAnalyticsGoogleAnalyticsSyncRoute
  ApiIntegrationsEmailSendRoute: typeof ApiIntegrationsEmailSendRoute
  ApiIntegrationsGoogleWorkspaceEventsRoute: typeof ApiIntegrationsGoogleWorkspaceEventsRoute
  ApiMeetingsLivekitTokenRoute: typeof ApiMeetingsLivekitTokenRoute
  ApiIntegrationsGoogleAnalyticsOauthCallbackRoute: typeof ApiIntegrationsGoogleAnalyticsOauthCallbackRoute
  ApiIntegrationsGoogleAnalyticsOauthStartRoute: typeof ApiIntegrationsGoogleAnalyticsOauthStartRoute
  ApiIntegrationsGoogleWorkspaceOauthCallbackRoute: typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
  ApiIntegrationsGoogleWorkspaceOauthUrlRoute: typeof ApiIntegrationsGoogleWorkspaceOauthUrlRoute
  ApiIntegrationsGoogleOauthCallbackRoute: typeof ApiIntegrationsGoogleOauthCallbackRoute
  ApiIntegrationsGoogleOauthUrlRoute: typeof ApiIntegrationsGoogleOauthUrlRoute
  ApiIntegrationsLinkedinOauthCallbackRoute: typeof ApiIntegrationsLinkedinOauthCallbackRoute
  ApiIntegrationsLinkedinOauthUrlRoute: typeof ApiIntegrationsLinkedinOauthUrlRoute
  ApiIntegrationsMetaOauthCallbackRoute: typeof ApiIntegrationsMetaOauthCallbackRoute
  ApiIntegrationsMetaOauthUrlRoute: typeof ApiIntegrationsMetaOauthUrlRoute
  ApiIntegrationsTiktokOauthCallbackRoute: typeof ApiIntegrationsTiktokOauthCallbackRoute
  ApiIntegrationsTiktokOauthUrlRoute: typeof ApiIntegrationsTiktokOauthUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/manifest/webmanifest': {
      id: '/manifest/webmanifest'
      path: '/manifest/webmanifest'
      fullPath: '/manifest/webmanifest'
      preLoaderRoute: typeof ManifestWebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/for-you': {
      id: '/_authed/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof AuthedForYouRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/api/proxy/file': {
      id: '/api/proxy/file'
      path: '/api/proxy/file'
      fullPath: '/api/proxy/file'
      preLoaderRoute: typeof ApiProxyFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/transcript': {
      id: '/api/meetings/transcript'
      path: '/api/meetings/transcript'
      fullPath: '/api/meetings/transcript'
      preLoaderRoute: typeof ApiMeetingsTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/schedule': {
      id: '/api/meetings/schedule'
      path: '/api/meetings/schedule'
      fullPath: '/api/meetings/schedule'
      preLoaderRoute: typeof ApiMeetingsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/reschedule': {
      id: '/api/meetings/reschedule'
      path: '/api/meetings/reschedule'
      fullPath: '/api/meetings/reschedule'
      preLoaderRoute: typeof ApiMeetingsRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/quick': {
      id: '/api/meetings/quick'
      path: '/api/meetings/quick'
      fullPath: '/api/meetings/quick'
      preLoaderRoute: typeof ApiMeetingsQuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/cancel': {
      id: '/api/meetings/cancel'
      path: '/api/meetings/cancel'
      fullPath: '/api/meetings/cancel'
      preLoaderRoute: typeof ApiMeetingsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/worker': {
      id: '/api/integrations/worker'
      path: '/api/integrations/worker'
      fullPath: '/api/integrations/worker'
      preLoaderRoute: typeof ApiIntegrationsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/schedule': {
      id: '/api/integrations/schedule'
      path: '/api/integrations/schedule'
      fullPath: '/api/integrations/schedule'
      preLoaderRoute: typeof ApiIntegrationsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/process': {
      id: '/api/integrations/process'
      path: '/api/integrations/process'
      fullPath: '/api/integrations/process'
      preLoaderRoute: typeof ApiIntegrationsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/manual-sync': {
      id: '/api/integrations/manual-sync'
      path: '/api/integrations/manual-sync'
      fullPath: '/api/integrations/manual-sync'
      preLoaderRoute: typeof ApiIntegrationsManualSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/cron': {
      id: '/api/integrations/cron'
      path: '/api/integrations/cron'
      fullPath: '/api/integrations/cron'
      preLoaderRoute: typeof ApiIntegrationsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/files/proxy': {
      id: '/api/files/proxy'
      path: '/api/files/proxy'
      fullPath: '/api/files/proxy'
      preLoaderRoute: typeof ApiFilesProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/clients': {
      id: '/api/debug/clients'
      path: '/api/debug/clients'
      fullPath: '/api/debug/clients'
      preLoaderRoute: typeof ApiDebugClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/client-summary': {
      id: '/api/dashboard/client-summary'
      path: '/api/dashboard/client-summary'
      fullPath: '/api/dashboard/client-summary'
      preLoaderRoute: typeof ApiDashboardClientSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/tasks': {
      id: '/_authed/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof AuthedDashboardTasksRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/socials': {
      id: '/_authed/dashboard/socials'
      path: '/socials'
      fullPath: '/dashboard/socials'
      preLoaderRoute: typeof AuthedDashboardSocialsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/projects': {
      id: '/_authed/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthedDashboardProjectsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/notifications': {
      id: '/_authed/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthedDashboardNotificationsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/meetings': {
      id: '/_authed/dashboard/meetings'
      path: '/meetings'
      fullPath: '/dashboard/meetings'
      preLoaderRoute: typeof AuthedDashboardMeetingsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/collaboration': {
      id: '/_authed/dashboard/collaboration'
      path: '/collaboration'
      fullPath: '/dashboard/collaboration'
      preLoaderRoute: typeof AuthedDashboardCollaborationRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/clients': {
      id: '/_authed/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof AuthedDashboardClientsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/analytics': {
      id: '/_authed/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/team': {
      id: '/_authed/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthedAdminTeamRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/issues': {
      id: '/_authed/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AuthedAdminIssuesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/health': {
      id: '/_authed/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthedAdminHealthRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/features': {
      id: '/_authed/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AuthedAdminFeaturesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/clients': {
      id: '/_authed/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthedAdminClientsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/dashboard/settings/': {
      id: '/_authed/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/proposals/': {
      id: '/_authed/dashboard/proposals/'
      path: '/proposals'
      fullPath: '/dashboard/proposals/'
      preLoaderRoute: typeof AuthedDashboardProposalsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/ads/': {
      id: '/_authed/dashboard/ads/'
      path: '/ads'
      fullPath: '/dashboard/ads/'
      preLoaderRoute: typeof AuthedDashboardAdsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/meetings/livekit/token': {
      id: '/api/meetings/livekit/token'
      path: '/api/meetings/livekit/token'
      fullPath: '/api/meetings/livekit/token'
      preLoaderRoute: typeof ApiMeetingsLivekitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/events': {
      id: '/api/integrations/google-workspace/events'
      path: '/api/integrations/google-workspace/events'
      fullPath: '/api/integrations/google-workspace/events'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/email/send': {
      id: '/api/integrations/email/send'
      path: '/api/integrations/email/send'
      fullPath: '/api/integrations/email/send'
      preLoaderRoute: typeof ApiIntegrationsEmailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/google-analytics/sync': {
      id: '/api/analytics/google-analytics/sync'
      path: '/api/analytics/google-analytics/sync'
      fullPath: '/api/analytics/google-analytics/sync'
      preLoaderRoute: typeof ApiAnalyticsGoogleAnalyticsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/settings/integrations': {
      id: '/_authed/dashboard/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/dashboard/settings/integrations'
      preLoaderRoute: typeof AuthedDashboardSettingsIntegrationsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/proposals/viewer': {
      id: '/_authed/dashboard/proposals/viewer'
      path: '/proposals/viewer'
      fullPath: '/dashboard/proposals/viewer'
      preLoaderRoute: typeof AuthedDashboardProposalsViewerRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/proposals/analytics': {
      id: '/_authed/dashboard/proposals/analytics'
      path: '/proposals/analytics'
      fullPath: '/dashboard/proposals/analytics'
      preLoaderRoute: typeof AuthedDashboardProposalsAnalyticsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/integrations/tiktok/oauth/url': {
      id: '/api/integrations/tiktok/oauth/url'
      path: '/api/integrations/tiktok/oauth/url'
      fullPath: '/api/integrations/tiktok/oauth/url'
      preLoaderRoute: typeof ApiIntegrationsTiktokOauthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok/oauth/callback': {
      id: '/api/integrations/tiktok/oauth/callback'
      path: '/api/integrations/tiktok/oauth/callback'
      fullPath: '/api/integrations/tiktok/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsTiktokOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/oauth/url': {
      id: '/api/integrations/meta/oauth/url'
      path: '/api/integrations/meta/oauth/url'
      fullPath: '/api/integrations/meta/oauth/url'
      preLoaderRoute: typeof ApiIntegrationsMetaOauthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/oauth/callback': {
      id: '/api/integrations/meta/oauth/callback'
      path: '/api/integrations/meta/oauth/callback'
      fullPath: '/api/integrations/meta/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/linkedin/oauth/url': {
      id: '/api/integrations/linkedin/oauth/url'
      path: '/api/integrations/linkedin/oauth/url'
      fullPath: '/api/integrations/linkedin/oauth/url'
      preLoaderRoute: typeof ApiIntegrationsLinkedinOauthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/linkedin/oauth/callback': {
      id: '/api/integrations/linkedin/oauth/callback'
      path: '/api/integrations/linkedin/oauth/callback'
      fullPath: '/api/integrations/linkedin/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsLinkedinOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/oauth/url': {
      id: '/api/integrations/google/oauth/url'
      path: '/api/integrations/google/oauth/url'
      fullPath: '/api/integrations/google/oauth/url'
      preLoaderRoute: typeof ApiIntegrationsGoogleOauthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/oauth/callback': {
      id: '/api/integrations/google/oauth/callback'
      path: '/api/integrations/google/oauth/callback'
      fullPath: '/api/integrations/google/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/oauth/url': {
      id: '/api/integrations/google-workspace/oauth/url'
      path: '/api/integrations/google-workspace/oauth/url'
      fullPath: '/api/integrations/google-workspace/oauth/url'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceOauthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/oauth/callback': {
      id: '/api/integrations/google-workspace/oauth/callback'
      path: '/api/integrations/google-workspace/oauth/callback'
      fullPath: '/api/integrations/google-workspace/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-analytics/oauth/start': {
      id: '/api/integrations/google-analytics/oauth/start'
      path: '/api/integrations/google-analytics/oauth/start'
      fullPath: '/api/integrations/google-analytics/oauth/start'
      preLoaderRoute: typeof ApiIntegrationsGoogleAnalyticsOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-analytics/oauth/callback': {
      id: '/api/integrations/google-analytics/oauth/callback'
      path: '/api/integrations/google-analytics/oauth/callback'
      fullPath: '/api/integrations/google-analytics/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleAnalyticsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/proposals/$proposalId/deck': {
      id: '/_authed/dashboard/proposals/$proposalId/deck'
      path: '/proposals/$proposalId/deck'
      fullPath: '/dashboard/proposals/$proposalId/deck'
      preLoaderRoute: typeof AuthedDashboardProposalsProposalIdDeckRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/ads/campaigns/$providerId/$campaignId': {
      id: '/_authed/dashboard/ads/campaigns/$providerId/$campaignId'
      path: '/ads/campaigns/$providerId/$campaignId'
      fullPath: '/dashboard/ads/campaigns/$providerId/$campaignId'
      preLoaderRoute: typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId': {
      id: '/_authed/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId'
      path: '/creative/$creativeId'
      fullPath: '/dashboard/ads/campaigns/$providerId/$campaignId/creative/$creativeId'
      preLoaderRoute: typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRouteImport
      parentRoute: typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminClientsRoute: typeof AuthedAdminClientsRoute
  AuthedAdminFeaturesRoute: typeof AuthedAdminFeaturesRoute
  AuthedAdminHealthRoute: typeof AuthedAdminHealthRoute
  AuthedAdminIssuesRoute: typeof AuthedAdminIssuesRoute
  AuthedAdminTeamRoute: typeof AuthedAdminTeamRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminClientsRoute: AuthedAdminClientsRoute,
  AuthedAdminFeaturesRoute: AuthedAdminFeaturesRoute,
  AuthedAdminHealthRoute: AuthedAdminHealthRoute,
  AuthedAdminIssuesRoute: AuthedAdminIssuesRoute,
  AuthedAdminTeamRoute: AuthedAdminTeamRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteChildren {
  AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute: typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute
}

const AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteChildren: AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteChildren =
  {
    AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute:
      AuthedDashboardAdsCampaignsProviderIdCampaignIdCreativeCreativeIdRoute,
  }

const AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteWithChildren =
  AuthedDashboardAdsCampaignsProviderIdCampaignIdRoute._addFileChildren(
    AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardAnalyticsRoute: typeof AuthedDashboardAnalyticsRoute
  AuthedDashboardClientsRoute: typeof AuthedDashboardClientsRoute
  AuthedDashboardCollaborationRoute: typeof AuthedDashboardCollaborationRoute
  AuthedDashboardMeetingsRoute: typeof AuthedDashboardMeetingsRoute
  AuthedDashboardNotificationsRoute: typeof AuthedDashboardNotificationsRoute
  AuthedDashboardProjectsRoute: typeof AuthedDashboardProjectsRoute
  AuthedDashboardSocialsRoute: typeof AuthedDashboardSocialsRoute
  AuthedDashboardTasksRoute: typeof AuthedDashboardTasksRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardProposalsAnalyticsRoute: typeof AuthedDashboardProposalsAnalyticsRoute
  AuthedDashboardProposalsViewerRoute: typeof AuthedDashboardProposalsViewerRoute
  AuthedDashboardSettingsIntegrationsRoute: typeof AuthedDashboardSettingsIntegrationsRoute
  AuthedDashboardAdsIndexRoute: typeof AuthedDashboardAdsIndexRoute
  AuthedDashboardProposalsIndexRoute: typeof AuthedDashboardProposalsIndexRoute
  AuthedDashboardSettingsIndexRoute: typeof AuthedDashboardSettingsIndexRoute
  AuthedDashboardProposalsProposalIdDeckRoute: typeof AuthedDashboardProposalsProposalIdDeckRoute
  AuthedDashboardAdsCampaignsProviderIdCampaignIdRoute: typeof AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteWithChildren
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardAnalyticsRoute: AuthedDashboardAnalyticsRoute,
  AuthedDashboardClientsRoute: AuthedDashboardClientsRoute,
  AuthedDashboardCollaborationRoute: AuthedDashboardCollaborationRoute,
  AuthedDashboardMeetingsRoute: AuthedDashboardMeetingsRoute,
  AuthedDashboardNotificationsRoute: AuthedDashboardNotificationsRoute,
  AuthedDashboardProjectsRoute: AuthedDashboardProjectsRoute,
  AuthedDashboardSocialsRoute: AuthedDashboardSocialsRoute,
  AuthedDashboardTasksRoute: AuthedDashboardTasksRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardProposalsAnalyticsRoute:
    AuthedDashboardProposalsAnalyticsRoute,
  AuthedDashboardProposalsViewerRoute: AuthedDashboardProposalsViewerRoute,
  AuthedDashboardSettingsIntegrationsRoute:
    AuthedDashboardSettingsIntegrationsRoute,
  AuthedDashboardAdsIndexRoute: AuthedDashboardAdsIndexRoute,
  AuthedDashboardProposalsIndexRoute: AuthedDashboardProposalsIndexRoute,
  AuthedDashboardSettingsIndexRoute: AuthedDashboardSettingsIndexRoute,
  AuthedDashboardProposalsProposalIdDeckRoute:
    AuthedDashboardProposalsProposalIdDeckRoute,
  AuthedDashboardAdsCampaignsProviderIdCampaignIdRoute:
    AuthedDashboardAdsCampaignsProviderIdCampaignIdRouteWithChildren,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  AuthedForYouRoute: typeof AuthedForYouRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  AuthedForYouRoute: AuthedForYouRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiHealthRouteChildren {
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PendingApprovalRoute: PendingApprovalRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ManifestWebmanifestRoute: ManifestWebmanifestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDashboardClientSummaryRoute: ApiDashboardClientSummaryRoute,
  ApiDebugClientsRoute: ApiDebugClientsRoute,
  ApiFilesProxyRoute: ApiFilesProxyRoute,
  ApiIntegrationsCronRoute: ApiIntegrationsCronRoute,
  ApiIntegrationsManualSyncRoute: ApiIntegrationsManualSyncRoute,
  ApiIntegrationsProcessRoute: ApiIntegrationsProcessRoute,
  ApiIntegrationsScheduleRoute: ApiIntegrationsScheduleRoute,
  ApiIntegrationsWorkerRoute: ApiIntegrationsWorkerRoute,
  ApiMeetingsCancelRoute: ApiMeetingsCancelRoute,
  ApiMeetingsQuickRoute: ApiMeetingsQuickRoute,
  ApiMeetingsRescheduleRoute: ApiMeetingsRescheduleRoute,
  ApiMeetingsScheduleRoute: ApiMeetingsScheduleRoute,
  ApiMeetingsTranscriptRoute: ApiMeetingsTranscriptRoute,
  ApiProxyFileRoute: ApiProxyFileRoute,
  ApiAnalyticsGoogleAnalyticsSyncRoute: ApiAnalyticsGoogleAnalyticsSyncRoute,
  ApiIntegrationsEmailSendRoute: ApiIntegrationsEmailSendRoute,
  ApiIntegrationsGoogleWorkspaceEventsRoute:
    ApiIntegrationsGoogleWorkspaceEventsRoute,
  ApiMeetingsLivekitTokenRoute: ApiMeetingsLivekitTokenRoute,
  ApiIntegrationsGoogleAnalyticsOauthCallbackRoute:
    ApiIntegrationsGoogleAnalyticsOauthCallbackRoute,
  ApiIntegrationsGoogleAnalyticsOauthStartRoute:
    ApiIntegrationsGoogleAnalyticsOauthStartRoute,
  ApiIntegrationsGoogleWorkspaceOauthCallbackRoute:
    ApiIntegrationsGoogleWorkspaceOauthCallbackRoute,
  ApiIntegrationsGoogleWorkspaceOauthUrlRoute:
    ApiIntegrationsGoogleWorkspaceOauthUrlRoute,
  ApiIntegrationsGoogleOauthCallbackRoute:
    ApiIntegrationsGoogleOauthCallbackRoute,
  ApiIntegrationsGoogleOauthUrlRoute: ApiIntegrationsGoogleOauthUrlRoute,
  ApiIntegrationsLinkedinOauthCallbackRoute:
    ApiIntegrationsLinkedinOauthCallbackRoute,
  ApiIntegrationsLinkedinOauthUrlRoute: ApiIntegrationsLinkedinOauthUrlRoute,
  ApiIntegrationsMetaOauthCallbackRoute: ApiIntegrationsMetaOauthCallbackRoute,
  ApiIntegrationsMetaOauthUrlRoute: ApiIntegrationsMetaOauthUrlRoute,
  ApiIntegrationsTiktokOauthCallbackRoute:
    ApiIntegrationsTiktokOauthCallbackRoute,
  ApiIntegrationsTiktokOauthUrlRoute: ApiIntegrationsTiktokOauthUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
