export type TaskDocumentImportPhase = 'idle' | 'dragging' | 'extracting' | 'analyzing' | 'review' | 'creating' | 'error';
export type TaskAssignmentStatus = 'resolved' | 'ambiguous' | 'unassigned';
export type TaskDueDateStatus = 'resolved' | 'missing' | 'unclear';
export type ProposedImportTask = {
    localId: string;
    title: string;
    description: string;
    priority: string;
    assignedTo: string;
    assignedToUserIds: string[];
    documentAssigneeNames: string[];
    dueDate: string;
    assignmentStatus: TaskAssignmentStatus;
    dueDateStatus: TaskDueDateStatus;
    dueDateHint: string | null;
    suggestions: string[];
    sourceExcerpt: string | null;
    include: boolean;
};
export type ProposedImportTaskFromServer = {
    title: string;
    description: string | null;
    priority: 'low' | 'medium' | 'high';
    assignedToUserIds: string[];
    documentAssigneeNames: string[];
    dueDateMs: number | null;
    assignmentStatus: TaskAssignmentStatus;
    dueDateStatus: TaskDueDateStatus;
    dueDateHint: string | null;
    suggestions: string[];
    sourceExcerpt: string | null;
};
