'use client'

import { useCallback, useMemo } from 'react'
import { Printer } from 'lucide-react'
import { Button } from '@/shared/ui/button'
import type { TaskRecord, TaskStatus } from '@/types/tasks'
import { formatStatusLabel, formatDate, formatPriorityLabel } from './task-types'
import { escapeHtml } from '@/lib/escape-html'
import { cn } from '@/lib/utils'
import './tasks-print.css'

type TaskPrintViewProps = {
  tasks: TaskRecord[]
  title?: string
  summary?: {
    total: number
    completed: number
    inProgress: number
    todo: number
  }
  onClose?: () => void
}

export function TaskPrintView({ tasks, title = 'Tasks', summary, onClose }: TaskPrintViewProps) {
  const tasksByStatus = useMemo(() => {
    const groups: Record<TaskStatus, TaskRecord[]> = {
      todo: [],
      'in-progress': [],
      review: [],
      completed: [],
      archived: [],
    }
    tasks.forEach(task => {
      groups[task.status].push(task)
    })
    return groups
  }, [tasks])

  const derivedSummary = useMemo(() => {
    return {
      total: tasks.length,
      completed: tasksByStatus.completed.length,
      inProgress: tasksByStatus['in-progress'].length,
      todo: tasksByStatus.todo.length,
    }
  }, [tasks, tasksByStatus])

  const calculatedSummary = summary ?? derivedSummary

  const handlePrint = useCallback(() => {
    window.print()
  }, [])

  return (
    <div className="tasks-print-container">
      {/* Print header - hidden on screen, visible in print */}
      <div className="tasks-print-header">
        <div>
          <h1 className="tasks-print-title">{title}</h1>
          <p className="tasks-print-meta">
            Printed on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
          </p>
        </div>
        {onClose && (
          <div className="no-print flex gap-2">
            <Button onClick={handlePrint} size="sm" className="gap-1">
              <Printer className="h-4 w-4" />
              Print
            </Button>
            <Button onClick={onClose} variant="outline" size="sm">
              Close
            </Button>
          </div>
        )}
      </div>

      {/* Summary cards */}
      <div className="tasks-print-summary">
        <div className="tasks-print-summary-item">
          <div className="tasks-print-summary-value">{calculatedSummary.total}</div>
          <div className="tasks-print-summary-label">Total</div>
        </div>
        <div className="tasks-print-summary-item">
          <div className="tasks-print-summary-value">{calculatedSummary.todo}</div>
          <div className="tasks-print-summary-label">To Do</div>
        </div>
        <div className="tasks-print-summary-item">
          <div className="tasks-print-summary-value">{calculatedSummary.inProgress}</div>
          <div className="tasks-print-summary-label">In Progress</div>
        </div>
        <div className="tasks-print-summary-item">
          <div className="tasks-print-summary-value">{calculatedSummary.completed}</div>
          <div className="tasks-print-summary-label">Completed</div>
        </div>
      </div>

      {/* Tasks by status */}
      {Object.entries(tasksByStatus).map(([status, statusTasks]) => {
        if (statusTasks.length === 0) return null
        return (
          <div key={status} className="tasks-print-group">
            <h2 className="tasks-print-group-title">
              {formatStatusLabel(status as TaskStatus)} ({statusTasks.length})
            </h2>
            {statusTasks.map((task) => (
              <PrintableTaskCard key={task.id} task={task} />
            ))}
          </div>
        )
      })}

      {/* Print footer */}
      <div className="tasks-print-footer">
        <p>Generated by Cohort Task Management • {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  )
}

function PrintableTaskCard({ task }: { task: TaskRecord }) {
  const isOverdue = task.dueDate && new Date(task.dueDate) < new Date() && task.status !== 'completed'

  return (
    <div className={cn(
      'task-print-card',
      isOverdue && 'task-print-overdue'
    )}>
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <h3 className="font-semibold text-sm">{task.title}</h3>
            <span className={cn(
              'task-print-status',
              task.status
            )}>
              {formatStatusLabel(task.status)}
            </span>
            <span className={cn(
              'task-print-priority',
              task.priority
            )}>
              {formatPriorityLabel(task.priority)}
            </span>
          </div>

          {task.description && (
            <p className="mb-2 line-clamp-2 text-xs text-muted-foreground">
              {task.description}
            </p>
          )}

          <div className="flex flex-wrap gap-3 text-xs text-muted-foreground">
            <span>📅 {task.dueDate ? formatDate(task.dueDate) : 'No due date'}</span>
            <span>👤 {(task.assignedTo ?? []).join(', ') || 'Unassigned'}</span>
            {task.client && <span>🏢 {task.client}</span>}
          </div>

          <div className="tasks-print-indicators mt-2">
            {(task.commentCount ?? 0) > 0 && <span>💬 {task.commentCount}</span>}
            {(task.timeSpentMinutes ?? 0) > 0 && <span>⏱ {Math.floor((task.timeSpentMinutes ?? 0) / 60)}h {(task.timeSpentMinutes ?? 0) % 60}m</span>}
            {(task.subtaskCount ?? 0) > 0 && <span>📋 {task.subtaskCount} subtasks</span>}
          </div>
        </div>
      </div>
    </div>
  )
}

// Standalone print button
export function PrintTasksButton({ tasks, title }: { tasks: TaskRecord[], title?: string }) {
  const handlePrint = useCallback(() => {
    // Create a hidden print container
    const printContainer = document.createElement('div')
    printContainer.className = 'tasks-print-container'
    document.body.appendChild(printContainer)

    // Render the print view to the container
    const safeTitle = escapeHtml(title || 'Tasks')
    const safePrintedOn = escapeHtml(new Date().toLocaleDateString())
    const printContent = `
      <div class="tasks-print-header">
        <h1 class="tasks-print-title">${safeTitle}</h1>
        <p class="tasks-print-meta">Printed on ${safePrintedOn}</p>
      </div>
      <div class="tasks-print-list">
        ${tasks.map(task => {
          const statusClass = String(task.status).replace(/[^a-z0-9-]/gi, '')
          const safeTaskTitle = escapeHtml(task.title)
          const safeStatusLabel = escapeHtml(formatStatusLabel(task.status))
          const safeDateLine = escapeHtml(task.dueDate ? formatDate(task.dueDate) : 'No due date')
          const assignees = (task.assignedTo ?? []).map((n) => escapeHtml(n)).join(', ')
          const safeAssignees = assignees.length > 0 ? assignees : 'Unassigned'
          return `
          <div class="task-print-card">
            <div class="flex items-start justify-between gap-4">
              <div class="flex-1">
                <div class="flex items-center gap-2 mb-1">
                  <h3 class="font-semibold text-sm">${safeTaskTitle}</h3>
                  <span class="task-print-status ${statusClass}">${safeStatusLabel}</span>
                </div>
                <p class="text-xs text-muted-foreground">
                  📅 ${safeDateLine} •
                  👤 ${safeAssignees}
                </p>
              </div>
            </div>
          </div>
        `
        }).join('')}
      </div>
    `

    printContainer.innerHTML = printContent

    // Print
    window.print()

    // Clean up
    setTimeout(() => {
      document.body.removeChild(printContainer)
    }, 1000)
  }, [tasks, title])

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handlePrint}
      className="gap-1.5 no-print"
    >
      <Printer className="h-4 w-4" />
      Print List
    </Button>
  )
}
